### PR TITLE
feat: uni-v2 staking txns support

### PR DESCRIPTION
**Pull request by vividwood**
## Description

Added support for Stake/Unstake transaction methods from uniV2 parser

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/1214

## Testing

Pull this PR https://github.com/shapeshift/web/pull/1798, build `unchained-client` and `asset-service` and link them to the `web`
Connect ethereum account which interacted with contract `0x212ebf9FD3c10F371557b08E993eAaB385c3932b`
Go to `Transaction History` page

## Screenshots (if applicable)

image

### CODE REVIEW

**Review by 0xApotheosis — COMMENTED** [review]
I've linked this locally with https://github.com/shapeshift/lib/pull/648 linked, and mocked a connection to the wallet `0xD137F4f8E45158B66739040aCC1eb970Dc276da0` via `chain-adapters`, and I'm still seeing a "Send" for TXID `0x05fbc178561e1645cfd31e5a5c3756cba5695df416d87e2819e6e60470d01270 `:

Screen Shot 2022-05-16 at 4 59 30 pm

This could also be a linking issue, as the tests in the `lib` PR indicate that this should work.

**Comment by 0xdef1cafe** [comment]
converting to draft until https://github.com/shapeshift/lib/pull/648 is merged

**Review by 0xApotheosis — APPROVED** [review]
This should be good to go once https://github.com/shapeshift/lib/pull/648 is in.

Local linking doesn't work right now due to the current configuration of `unchained-client` with Docker, though @kaladinlight did a test via `unchained` and it worked as expected for a `staked` transaction.

**Comment by vividwood** [comment]
final view
image

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by elmutt** [comment]
@vividwood this pr is being deployed to prod today but for some reason during testing it wasnt working. Suspect it could be related to the wrong package version of asset-service or unchained-client being used.

Can you possibly take a look at this again and figure out whats wrong?

**Comment by kaladinlight** [comment]
> @vividwood this pr is being deployed to prod today but for some reason during testing it wasnt working. Suspect it could be related to the wrong package version of asset-service or unchained-client being used.
> 
> We are going to re-open this issue if you want to take another look at what could be wrong

This is on the unchained end. Since we are still parsing transaction in the ingester, we need to bump the package there. I am getting that updated and we can test again and it should be working as expected at that point.

**Comment by kaladinlight** [comment]
@vividwood I can confirm seeing the stake transaction row at https://d65ee710.web-29e.pages.dev/ after the `unchained-client` package bump in unchained. The asset icon and value is not displaying however. Confirmed locally against `@shapeshiftoss/asset-service v4.1.0` that the asset icon and value display correctly, that should be the last req for this feature to be complete

**Comment by vividwood** [comment]
> @vividwood I can confirm seeing the stake transaction row at https://d65ee710.web-29e.pages.dev/ after the `unchained-client` package bump in unchained. The asset icon and value is not displaying however. Confirmed locally against `@shapeshiftoss/asset-service v4.1.0` that the asset icon and value display correctly, that should be the last req for this feature to be complete

Thanks, completely forgot to bump versions, sorry.

**Comment by vividwood** [comment]
> @vividwood I can confirm seeing the stake transaction row at https://d65ee710.web-29e.pages.dev/ after the `unchained-client` package bump in unchained. The asset icon and value is not displaying however. Confirmed locally against `@shapeshiftoss/asset-service v4.1.0` that the asset icon and value display correctly, that should be the last req for this feature to be complete

https://github.com/shapeshift/web/pull/1856

**Pull request merged**
