### PR TITLE
feat: enable thorchain swapper + savers

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

Effectively a subset of https://github.com/shapeshift/web/pull/7692, re-enables:

- THORChain swapping
- THORChain savers (view, deposit, withdraw)

## Issue (if applicable)

N/A - post hard-fork admin

## Risk

> High Risk PRs Require 2 approvals

Medium 

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

THORChain swapping and savers vaults

## Testing

Ensure the following functionality works:

- THORChain swapping
- THORChain savers (view positions, deposit, withdraw)

See my related testing here: https://github.com/shapeshift/web/pull/7692#pullrequestreview-2288636094

### Engineering

☝️

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

☝️

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by woodenfurniture** [comment]
# Testing notes

### RUNE -> ATOM trade

❌ Unable to trade from RUNE -> ATOM. Also attempted RUNE -> AVAX with same error:

```
{
    "message": "failed to broadcast transaction: codespace: sdk, code: 4, description: unauthorized"
}
```

image

### THORChain savers deposit

ATOM deposit successful ✅, but app doesn't react to transaction completion ❓. The transaction is complete and visible in a new tab. Unsure if this is an issue already in production.

image
image

**Review by woodenfurniture — CHANGES_REQUESTED** [review]
Linking here to prevent accidental merge

https://github.com/shapeshift/web/pull/7703#issuecomment-2336912078

**Comment by 0xApotheosis** [comment]
Interesting @woodenfurniture, that's the same network response I got when attempting to use LPs when doing the initial post hardfork testing:

```
message: "failed to broadcast transaction: codespace: sdk, code: 4, description: unauthorized"
```

**Review by gomesalexandre — APPROVED** [review]
Tested locally - as discussed with @0xApotheosis, getting this in to unstuck savers and swapper, but *not* RUNEPool/RUNE swaps.

- Savers are bakk (but not RUNEPool, which is correct as RUNE is currently borked)
  image
- Savers withdraw (non-RUNE)
  - Inbound:
    https://live.blockcypher.com/doge/tx/84603cea42161821c7959ee3a677209664b4a0b751085ce023492c5480b3161f/
  - Outbound:
    image
    image
- Savers deposits (non-rune):
  https://jam.dev/c/b3b714c5-d275-4fd6-a159-05048c66523b
- Non-RUNE swap:
  - Inbound:
    https://jam.dev/c/94e984c4-5465-4143-ae47-572feab4aafa
  - Outound: I wasn't able to get to a confirmed stage either, similarly to what @woodenfurniture has found out with ATOM deposits. Attributing this to intermittent CosmosHub shenanigans - note the Tx also didn't show up after a tab refresh but is happy on-chain
    https://www.mintscan.io/cosmos/tx/6EAF5DBEACE63E47D1F0F7F64EB742A30134CA13E3B33B5FF39907902AC5C4EB?height=22105728
- Multi-hop sanity check (Li.Fi):
  https://jam.dev/c/943f9332-86ad-4417-9769-52b23535931d

**Pull request merged**
