### PR TITLE
feat: make runepool great again post hardfork

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Does what it says on the box.

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/7707

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

None

## Testing

- Ensure legacy THOR chain positions are happy
- Ensure it is possible to deposit into RUNEPool positions on the hardforked THOR chain.

### Engineering

- ^

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

- ^

## Screenshots (if applicable)

- develop
  Screenshot 2024-09-09 at 21 53 59
  Screenshot 2024-09-09 at 22 14 57

- This diff

image
image
image

### CODE REVIEW

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
- I updated the env using `yarn env dev`
- Cache clear
- Import a native wallet
- Trying to deposit into runepool: https://jam.dev/c/2d4cbf29-20ee-4343-b7fb-300ce16b8b1d

I have an error:

```"failed to broadcast transaction: codespace: sdk, code: 4, description: unauthorized"```

Reproduced on 2 browsers, can you reproduce on your side?

**Comment by kaladinlight** [comment]
Just a side note: https://indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5

midgard exposes a `/runepool` endpoint that gives us the timestamp without needing to route by block.

**Comment by kaladinlight** [comment]
> * I updated the env using `yarn env dev`
> * Cache clear
> * Import a native wallet
> * Trying to deposit into runepool: https://jam.dev/c/2d4cbf29-20ee-4343-b7fb-300ce16b8b1d
> 
> I have an error:
> 
> `"failed to broadcast transaction: codespace: sdk, code: 4, description: unauthorized"`
> 
> Reproduced on 2 browsers, can you reproduce on your side?

MM snaps are broken when sending thorchain txs atm if you are using that. Otherwise, make sure you ran `yarn` to pull the latest hdwallet dependency with the fork changes.

**Comment by gomesalexandre** [comment]
> Just a side note: [indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5](https://indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5)
> 
> midgard exposes a `/runepool` endpoint that gives us the timestamp without needing to route by block.

Happy to do that as a follow-up since this changes logic a tad bit, and I believe there is still value in exposing v1 THORNode, WDYT @kaladinlight ?

**Comment by kaladinlight** [comment]
> > Just a side note: [indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5](https://indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5)
> > midgard exposes a `/runepool` endpoint that gives us the timestamp without needing to route by block.
> 
> Happy to do that as a follow-up since this changes logic a tad bit, and I believe there is still value in exposing v1 THORNode, WDYT @kaladinlight ?

quick spot check doesn't appear like we do any historical queries against the node pre fork besides this. would say we add it if we need it, but no point otherwise.

**Review by NeOMakinG — APPROVED** [review]
image

https://viewblock.io/thorchain/tx/F3552ED50A3EB7B847A03E26B92EDA5E15A2957D1274E03D8924FA23325868A1

Deposit does works, I couldn't test any withdraw as I don't have any opportunities older than 90 days of course!

Deposit into another position looks fine too: https://snowtrace.dev/tx/0x0f4f92f2582b1ac4b5618237336f90371e07855fa34e3fc74466693645647cd1

Withdraw from another position too: https://snowtrace.dev/tx/0xffb383f7e08867def37e013d0082558565e1f4a382c85d428cf5fb9a46e90680

Even though UI update seems borked (https://github.com/shapeshift/web/issues/7712)

**Comment by gomesalexandre** [comment]
> > > Just a side note: [indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5](https://indexer.thorchain.shapeshift.com/v2/runepool/thor10prpfj07j6a7rvtd5tfqhdzp8xsypzatfrc2v5)
> > > midgard exposes a `/runepool` endpoint that gives us the timestamp without needing to route by block.
> > 
> > 
> > Happy to do that as a follow-up since this changes logic a tad bit, and I believe there is still value in exposing v1 THORNode, WDYT @kaladinlight ?
> 
> quick spot check doesn't appear like we do any historical queries against the node pre fork besides this. would say we add it if we need it, but no point otherwise.

Sounds sane to me: 549a2e41586b03debdb72d1273e6b3631806b1bb - confirmed this works on accounts with a position after a full cache clear:
Screenshot 2024-09-09 at 23 51 25

And inactive ones too:

Screenshot 2024-09-09 at 23 52 17

**Review by NeOMakinG — APPROVED** [review]
Re test

Deposit is happy
image
https://viewblock.io/thorchain/tx/C844C0B6D3AE86AFD37958A3A1BDD3F63807B02C1F5B0213B0E91E5BEBE30BC0

Legacy position is happy
image

**Pull request merged**
