### PR TITLE
Feat try without wallet

### LINKED ISSUE #895: Allow use of app without connected wallet/"demo mode"
# Overview

Many users have requested to be able to use the app (app.shapeshift.com) without first connecting a wallet. This makes sense from an engagement perspective - people want to see what things look and feel like before they use it.

# Reference

- instantiate a demo wallet like shown https://github.com/shapeshift/hdwallet/pull/452/commits/e59e755b6403cdfd2bbb331df2a0f535eef00a31#diff-673a1350d3a18db303ae7b7494c175c13e74e0dbd8faef3b1200d9708b028f9aR334-R335
- make an initial PR to update the `useWallet` hooks to provide an `isDemoWallet` boolean

# Guidance

At a high level, the app should be as functional as possible, without the user being able to get into a broken state.

- Use the `useWallet` hook to detect the presence (or rather, lack thereof) of a wallet for logic
- Add a grey button to the splash screen below the Connect Wallet, saying "Try without a wallet..."
- Redirect to [Bitcoin asset page](https://app.shapeshift.com/assets/bitcoin) as the first screen instead of `/dashboard`
- Disable send/receive buttons on asset pages
- Hide account page link in nav
- Hide accounts from asset pages
- Hide balance chart buttons, make sure pages default to price charts
- Disconnect wallet button should disconnect wallet and clear portfolio, but not boot the user back out to the `connect-wallet` screen
- Trade dialog
  - Sell assets should be fetched from all assets list, not users portfolio assets
  - Confirm trade button should be disabled
- Defi vaults - show modal but stop the user at step 1

# Acceptance criteria

- No regressions across the app
- App is usable to the fullest extent possible without connecting a wallet

# Bounty Hunters 
- Join our discord [here](https://discord.gg/shapeshift). Once you join you can see more about this issue [here](https://discord.com/channels/554694662431178782/873244924026449940/925799058537336853)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info

### PR DESCRIPTION
**Pull request by gall0x**
## Description

WIP for #895 

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #895 

## Testing

Please outline all testing steps

WIP

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
hi @gall0x - thanks for the PR. are you aware this bounty has already been assigned to @amitojsingh366? as it was assigned to him first, we're obliged to review and accept his PR first. 

please keep an eye on https://gitcoin.co/shapeshift/bounties - there will be many more bounties posted.

**Comment by amitojsingh366** [comment]
Hi yes @gall0x this was assigned to me :(

**Comment by gall0x** [comment]
Yes, sorry, I didn't see it. @0xdef1cafe @amitojsingh366

**Comment by amitojsingh366** [comment]
> > Hi yes @gall0x this was assigned to me :(
> 
> This has not been assigned yet, no one has been approved to work on it in gitcoin as of yet. Will do that today.

Really? I thought @0xdef1cafe had assigned me to this one

**Pull request closed without merging**
