### PR TITLE
fix: display correct distribution of affiliate revenue to stakers

### PR DESCRIPTION
**Pull request by woodenfurniture**
## Description

Ensures we display the correct RUNE amount distributed to stakers on rFOX dashboard.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

See https://discord.com/channels/554694662431178782/886041582422356018/1256052603364573256

Low risk - display concern only.

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

Check the RUNE reward amounts are correct.

### CODE REVIEW

**Review by gomesalexandre — APPROVED** [review]
Tested locally, confirmed amounts are /2 against develop and we weren't doing any halving calculations before, so looks sane to me.

image

**Review by NeOMakinG — APPROVED** [review]
## This branch
image

## Develop
image

Looks good, trusting @gomesalexandre on the fact that we don't divide them previously as I'm not so aware of the codebase on that part

**Comment by NeOMakinG** [comment]
Waiting for @kaladinlight confirmation that the revenue endpoint returns the revenues not divided by 2 already

**Comment by twblack88** [comment]
@0xApotheosis just for reference let's keep #7264 as is. 

Totally normal seeing "staked balance" twice..... instead of my silly suggestion for appending the rFOX string at the header of the page. It's silly. We were silly.

**Comment by 0xApotheosis** [comment]
Sounds good @twblack88 😀

**Review by 0xApotheosis — APPROVED** [review]
Screenshot 2024-07-01 at 10 42 28 AM

Looks good ser.

**Pull request merged**
