### PR TITLE
chore: upgraded hdwallet library to 1.19.0

### LINKED ISSUE #526: Gas fee estimate for trade different than Metamask
When a user previews a trade on V2 using Metamask, the gas fee estimate given is significantly different than the gas fee given by the Metamask extension when signing the trade.

- visit https://app.shapeshift.com/dashboard
- connect metamask
- preview trade ETH/ERC-20-ETH/ERC-20
- take note of the gas fee estimate
- click "confirm and trade"
- see the fee that Metamask is having you use to sign the TX

Screen Shot 2021-12-01 at 12 06 13 PM
Screen Shot 2021-12-01 at 12 06 33 PM
Screen Shot 2021-12-01 at 12 06 40 PM

A/C:
 - The estimated gas fee should be much closer to the actual gas fee that Metamask pulls when completing a trade on V2.
 - Update and extend any tests associated with this flow

### PR DESCRIPTION
**Pull request by Neurone**
## Description

Upgraded hdwallet library to 1.19.0; see #526 

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

`closes #526`.

## Risk

All tests run fine.

## Testing

All tests run fine.

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
thanks for this @Neurone! can you please fix merge conflicts and i'll approve?

**Comment by cjthompson** [comment]
in `package.json`
```
    "path-browserify": "^1.0.1",
```

in `react-app-rewired.config.js`
```
          path: require.resolve('path-browserify'),
```

**Comment by Neurone** [comment]
Branch rebased.

**Comment by 0xdef1cafe** [comment]
@mrnerdhair @bithighlander @pastaghost this new version of hdwallet is upsetting the web builds w.r.t. polyfills - can one of you please take a look?

**Comment by 0xdef1cafe** [comment]
thanks @Neurone  - closing in favor of https://github.com/shapeshift/web/pull/1101 so we can get it merged

**Pull request closed without merging**
