### PR TITLE
feat(no-overfetching): add getYearnInvestor singleton

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Paranoia PR against overfetching, makes sure we instantiate `new YearnInvestor()` only once, reducing the number of Infura calls.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

Ensure Yearn is still working as expected and no console errors are displayed.

## Testing

- There is only a single call to Infura initiating from YearnProvider 
- Yearn feature is showing no regressions

### Engineering

- See top-level testing notes

### Operations

- See top-level testing notes
- Initiator can be seen by clicking a specific request, then clicking "Initiator"
image

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2780** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2780" target="_blank">Graphite</a> 
    * **PR #2782** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2782" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2782?utm_source=stack-comment).

**Review by 0xApotheosis — APPROVED** [review]
Nice one. 

Does what is says on the box, Yearn still working as expected, and no erroneous console errors.

**Comment by cjthompson** [comment]
Have you see [react-singleton-hook](https://www.npmjs.com/package/react-singleton-hook)?

**Comment by gomesalexandre** [comment]
> Have you see [react-singleton-hook](https://www.npmjs.com/package/react-singleton-hook)?

Very interesting one! If it does what it says on the docs, I can definitely see some areas we'd want to use it, but it's probably overkill to write a hook for the sole purpose of instantiating `YearnInvestor` in that case, however.

**Pull request merged**
