### PR TITLE
fix(handleDisconnect): use RESET_STATE wallet action to handle disconnect

### LINKED ISSUE #1610: Gracefully handle not completing the KeepKey initialization flow
### Overview

The user can select the close or back buttons to exit the initialization flow, possibly by accident. This will drop them into a broken state until they choose to disconnect their wallet. This may be a non-obvious fix, especially if the user got into the state accidentally.

165401124-20b3d3ed-632a-41c6-a086-dbdc6bbf3495

### References and additional details

We'll want to update the `onClose()` model handler (and any other relevant handlers) to ensure the app is left in a happy state.

### Acceptance Criteria

If a user disconnects their KeepKey close the modal and kick them back to the connect wallet flow. Also, send the user to the wallet connection screen if they ever close (x) out of the recovery modal.

Product to confirm.

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by brymut**
## Description

Switched to using `RESET_STATE` to take user back to connect wallet screen instead of existing flipping between `SET_WALLET_MODAL` payload. 

[My previous PR changes](https://github.com/shapeshift/web/pull/3440/files) to the `onClose` handler for the modal from last week may have also helped with the behavior for taking the user back to connect wallet screen. And the removal of the back button from this modal will also help with reducing the risk of putting user into the undesired state.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1610 

## Risk

UI related, no connected wallet, minor risk imo.

### Engineering

- Connect a KeepKey device that has been factory reset/wiped
- Pair the KeepKey device
- The "Get Started with Keepkey" Modal should appear.
- Either close the modal or disconnect Keepkey device and you should be led back to the initial connect wallet flow.

### Operations

Same steps as in Engineering apply.

## Screenshots (if applicable)

https://user-images.githubusercontent.com/14836056/207625932-1aa0369d-594f-467c-a5bd-11034f39d667.mov

### CODE REVIEW

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
Thanks for the detailed PR template @brymut.

This change seems to cause some kind of exception feedback loop when disconnecting. It also breaks subsequent UI reconnections until the KeepKey is unplugged, and re-plugged.

Screenshot 2022-12-20 at 5 26 27 pm

Previously, it would only throw twice on `transferIn` then `transferOut`. And for these 2, we should really catch them to meet the "gracefully handle" part of this ticket.

**Comment by 0xApotheosis** [comment]
@brymut I've converted this to draft until it's ready for another review 🙏

**Comment by brymut** [comment]
Hi again @0xApotheosis , I can't seem to be able to recreate this issue when I disconnect, recording 👇
https://user-images.githubusercontent.com/14836056/210400448-1c8e7846-3c2e-4ea4-be58-eeb77bb23f34.mov

**Comment by brymut** [comment]
Hi @0xApotheosis could you please have another look?

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
@brymut this is still causing the same regression noted before.

I've recorded a screen capture for you to hopefully assist: https://www.youtube.com/watch?v=csRRq7OAkgg

**Comment by 0xdef1cafe** [comment]
as discussed w/ @pastaghost kicking this to draft until necessary changes are made in `hdwallet` for this

**Comment by 0xdef1cafe** [comment]
closing as stale, plz reopen if required

**Pull request closed without merging**
