### PR TITLE
fix: display lending positions post-hardfork shenanigans

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Does precisely what it says on the box.
NOTE: While this fixes displaying positions, repays still can't be done because of close endpoint shenanigans: https://discord.com/channels/838986635756044328/1283906886051172427/1284230662517424254

## Issue (if applicable)

closes N/A

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

Low - ensure "Available Pools" is still displaying no pools

## Testing

- "Available Pools" is still empty
- With a frame (or rather, Rabby watch-only address as Frame MM injection is currently borked following upstream changes) and a known borrower from the borrowers endpoint (https://paw.pt/i39K7GP3), lending positions are displayed

### Engineering

- ^

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

- ^

## Screenshots (if applicable)

- develop

Screenshot 2024-09-13 at 20 20 00

- this diff

Screenshot 2024-09-13 at 21 22 37

### CODE REVIEW

**Review by 0xApotheosis — COMMENTED** [review]
Hmm, I'm wondering if we need to tweak the filter further.

Prod:

Screenshot 2024-09-14 at 6 41 03 AM

This branch:

Screenshot 2024-09-14 at 6 41 21 AM

Note my loan ratio now correctly shows, but I get infinite skeletons for collateral and debt values.

**Comment by gomesalexandre** [comment]
> Hmm, I'm wondering if we need to tweak the filter further.
> 
> Prod:
> 
> Screenshot 2024-09-14 at 6 41 03 AM
> This branch:
> 
> Screenshot 2024-09-14 at 6 41 21 AM
> Note my loan ratio now correctly shows, but I get infinite skeletons for collateral and debt values.

Retested both with a known borrower:

image

and with my own addy (no loans atm):

image


and couldn't repro. @0xApotheosis is this happening deterministically for you? 🤔

**Comment by 0xApotheosis** [comment]
It's deterministic for me, yeah (clean cache and all) - I'll see if I can work out what's up.

When I use the same seed on THORSwap I correctly see my loan:

Screenshot 2024-09-14 at 3 33 59 PM

**Comment by gomesalexandre** [comment]
gm @0xApotheosis! 2d0e08f433e6a4cf01c3d3abd5463c087b4bcb07

Confirmed this was an actual bug - non-lending enabled pools will error, which we should not fetch (and did not previously) but now will as we lost the ability to narrow our collateral pools proper - at least when fetching positions - "Available Pools" is still happy (though not user-facing happy as pools are still full upstream as they've been for many months!)

Screenshot 2024-09-16 at 13 15 43

**Review by 0xApotheosis — APPROVED** [review]
gm indeed @gomesalexandre! My loans are great again 😌 

Screenshot 2024-09-16 at 7 22 38 PM

**Pull request merged**
