### PR TITLE
feat: hyperlink in description 

### LINKED ISSUE #1020: Enable hyperlinks in custom, hardcoded asset descriptions (pt 2)
### Overview

ShapeShift web now supports custom asset descriptions, which can be added here: https://github.com/willyogo/lib/blob/patch-1/packages/asset-service/src/service/descriptions.json

Product plans on sourcing descriptions/instructions for each of the assets supported on Yearn which lack liquidity on DEXs, ie. LP tokens like crvCRVETH (see https://github.com/shapeshift/lib/pull/350 and [evergreen bounty](https://www.notion.so/shapeshift/Write-Asset-Descriptions-for-LP-tokens-9e29732831a544698e48f61e355abfa1))

Currently hyperlinks in asset descriptions are blocked due to the security vulnerability of programmatically importing descriptions from a 3rd party (Coingecko). However, because these hyperlinks will be reviewed and hardcoded, we can enable hyperlinks via markdown.

For all custom descriptions, we want the hyperlinks to be active and not blocked. Non-custom descriptions (from 3rd party) should be blocked. If the link is external (not app.shapeshift.com), it should open up in a new browser tab. If the link is internal (app.shapeshift.com), it should be routed to correct page in the app.

### Reference

In order to implement this feature, research needs to be done for a packages/plugins to convert markdown hyperlinks to html link tags, given the description will be in markdown format. The conversion will probably need to be done in the `AssetHeader.tsx`.

The `Asset` type has a `isTrustedDescription` property that can be used to determine if the description is trusted or not. This can be used inside of `AssetHeader.tsx` to determine if the description needs to be sanitized or not.

### Acceptance Criteria

- If an asset description includes a markdown hyperlink, the text is linked.
- If the link is external (not app.shapeshift.com), it opens in a new tab
- If the link is internal (app.shapeshift.com), it opens in the same tab
- Hyperlinks use the current styling in the app (light blue text link)

### Screenshots/Mockups

_No response_

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### PR DESCRIPTION
**Pull request by DhruvJain1122**
closes #1020

### CODE REVIEW

**Comment by DhruvJain1122** [comment]
I wasn't able to find isTrustedDescription property, for now, all description URL are converted into hyperlink

**Comment by gomesalexandre** [comment]
> I wasn't able to find isTrustedDescription property, for now, all description URL are converted into hyperlink

Hey @DhruvJain1122, thanks for the contribution!
The `isTrustedDescription` will be included as an optional property of the `Asset` type in https://github.com/shapeshift/lib/pull/357/files#diff-bc09084a5595dff54122b864f8a3718cf0403c148a7b6b667452b710bdaaf8b5R54 but unfortunately, it is still in CR.
You can checkout this branch in lib, and link the lib package to web to test it out.

**Comment by DhruvJain1122** [comment]
I have added it, can you give it a check.
Also, Is there any trusted description?

**Comment by DaoDev44** [comment]
@0xean - Got it! I was not aware of that. Sorry about the mix up @DhruvJain1122

**Comment by 0xean** [comment]
closing this PR and re-opening the bounty due to not following coding standards.

**Pull request closed without merging**
