### PR TITLE
perf: skip assets fetching if already in state

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Ensures we don't "fetch" (or rather, load from the build), the 5ish Mb `generatedAssetData.json` if the asset slice is already populated. If it is, it means we've fetched all assets, and shouldn't:

 - re-"fetch" again, or in this case, rather instantiate `AssetService`
 - upsert, since this is effectively going to be a no-op, but is still going to come as a performance cost

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

Ensure assets are still loaded, either on a refresh, or on a fresh session with no cache

## Testing

 - See risks ☝🏽 
 
### Engineering

 - See risks ☝🏽 

### Operations

 - See risks ☝🏽

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #5518** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5518" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5518?utm_source=stack-comment).

**Comment by kaladinlight** [comment]
We should make note or at least dev announcement that we will need to do asset slice migrations when regenerating asset data for users to get the new data using this strategy.

**Comment by 0xApotheosis** [comment]
> We should make note or at least dev announcement that we will need to do asset slice migrations when regenerating asset data for users to get the new data using this strategy.

Probably add it as an info output to the asset generation script, where once it's finished it tells the dev that a migration will be needed before the changes will take effect.

**Comment by gomesalexandre** [comment]
> Probably add it as an info output to the asset generation script, where once it's finished it tells the dev that a migration will be needed before the changes will take effect.

smort @0xApotheosis ! 6c6e1b27a5860973007f44de7315410b5cc96b77

**Review by kaladinlight — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
