### PR TITLE
fix(types): change buy/sellAssetAccountNumber type

### PR DESCRIPTION
**Pull request by brymut**
## Description

Continuation of https://github.com/shapeshift/lib/pull/752
To change the name and type of `buyAssetAccountId` and `sellAssetAccountId` to `buyAssetAccountNumber` and `sellAssetAccountNumber` respectively from string to number.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Fixes https://github.com/shapeshift/lib/issues/679

### CODE REVIEW

**Comment by brymut** [comment]
Hi @elmutt, second PR addressing https://github.com/shapeshift/lib/issues/679

**Review by gomesalexandre — DISMISSED** [review]
LGTM after reviewing https://github.com/shapeshift/lib/pull/752 - I can't find any remaining references of `buyAssetAccountId` and `sellAssetAccountId` here, and the renamed usages are properly using numbers as a value.
Having some issues with linking `@shapeshiftoss/swapper`, so consider this review an untested stamp.

**Comment by elmutt** [comment]
happy to merge this once tests are fixed and lib pr is merged

**Comment by brymut** [comment]
> fix cypress tests

Cypress tests pass locally, aren't the CI issues being caused by not having the type from the related PR? https://github.com/shapeshift/lib/pull/752 @0xdef1cafe or am I missing something?

**Comment by elmutt** [comment]
> > > fix cypress tests
> > 
> > 
> > Cypress tests pass locally, aren't the CI issues being caused by not having the type from the related PR? [shapeshift/lib#752](https://github.com/shapeshift/lib/pull/752) @0xdef1cafe / @elmutt / @gomesalexandre or am I missing something?
> 
> Still having issues with linking swapper locally so I can't test it out, but yes, the failing tests should be because of the mismatch in signatures, because the version isn't bumped here.
> 
> Let's make this PR a draft until lib is merged and published.

I was able to test linked locally and its working good

**Comment by gomesalexandre** [comment]
Will accept this one after lib PR is merged, swapper dependency is bumped, and review is re-opened.

**Comment by elmutt** [comment]
closed in:

https://github.com/shapeshift/web/pull/2005

we merged this asap in another PR so web would be updated right away with no problem.

The bounty is complete can can be paid

**Pull request closed without merging**
