### PR TITLE
fix: comment the explanations inside pr template

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

Noticed that sometimes contributors forget to remove the explanations from their Pull Request.

Also, it's easier for reviewers and maintainers to detect empty parts because they will really be empty!

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Risk

No risk

## Testing

Can't really test until it's merged

### CODE REVIEW

**Comment by 0xApotheosis** [comment]
I understand why you've suggested this change, but I'm not convinced it's the right approach.

Commenting out the placeholder instructions makes them useless, as notes such as the below won't be seen by contributors, and we'll likely get lower quality PR descriptions as a result:

```markdown
If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.
```

**Comment by NeOMakinG** [comment]
> I understand why you've suggested this change, but I'm not convinced it's the right approach.
> 
> 
> 
> Commenting out the placeholder instructions makes them useless, as notes such as the below won't be seen by contributors, and we'll likely get lower quality PR descriptions as a result:
> 
> 
> 
> ```markdown
> 
> If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.
> 
> ```

I won't cry if you don't accept it, feel free to merge or close it depending on what the team choose 

- I would prefer to get an empty PR description than a description full of explanations, it's way easier to detect. 
- Comments are existing in order to be read, overwise we wouldn't comment our code

I don't really get why contributor wouldn't see it as a comment, as it's almost the same when you create the Pr, the only difference is when you already created it

**Review by 0xApotheosis — APPROVED** [review]
Ah I'm with you - this will still show the description when creating the PR, but hide it from the preview/created PR - yep, this gets my vote 🔥

**Review by gomesalexandre — APPROVED** [review]
That looks good! At first I was slightly concerned about these changes potentially hiding the unchanged template text from the posted description, but as we've discussed, seeing blanks would be spotted visually as fast, if not faster and would make it clear something hasn't been filled.

**Review by theoboldfrazier — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
