### PR TITLE
feat: savers withdraw not enough funds

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

QoL for ops to stop receiving "WHERE ME MONESE" tickets.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/5821

## Risk

None?

## Testing

- Have a UTXO savers position, but not enough fundus for withdraw + reconciliation (e.g BTC, which when you take the two into account, can be quite a high missing amount)
- Ensure the copy looks good
- Ensure the displayed address looks good
- Ensure the copy button copies your address to send fundus to

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

Screenshot 2023-12-18 at 21 22 27

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* `develop`
  * **PR #5885** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5885?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5885?utm_source=stack-comment).

**Comment by woodenfurniture** [comment]
wasnt able to test this because when i deposit the transaction doesnt actually execute. I see the following error in the console:
image

`src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx`
image

I do get a tx link, but its a dead link:
https://snowtrace.dev/tx/0x6e9aa8af5c9bad176074e7c64bf7af82274d10746e4175e4a0985b51e34eba2e

Just ran it again and got a different issue depositing:

https://github.com/shapeshift/web/assets/125113430/019c344a-c3fe-447f-a4e5-cb5fc861f6d0

**Comment by woodenfurniture** [comment]
finally got around to testing this
image

confirmed withdrawal with insufficient funds show the correct warning, copy looking good and copy address button working correctly.

Also noted an unrelated issue which I've ticketed in [#5933](https://github.com/shapeshift/web/issues/5933)

**Review by woodenfurniture — APPROVED** [review]

**Comment by woodenfurniture** [comment]
Ok there's something definitely weird going on with the checks here. I actually transferred slightly more than recommended amount and tried to withdraw and it would no let me withdraw because it didnt see the new balance. 

### Here's a list of steps I followed:

1. deposited whole balance minus ~0.5 doge
2. tested that gas check ui (this PR) warns of insufficient balance, "need at least 1.18 DOGE" ✅
3. wanted to test that the warning would go away with enough balance. Swapped RUNE -> DOGE and received 2.16 DOGE (more than enough to cover the warning)
4. went back into earn page and tried to withdraw. This time got "need at least 0.92 DOGE" ❓
5. copied the address from the warning, and transferred my whole DOGE balance to that address
6. DOGE received into the same account, wtf ok so the account is definitely my own account and the correct one too ✅
7. went back into earn page again, this time UI is happy for me to withdraw. Weird because my account balance did not change ❓

### Screenshots

Swapped RUNE -> DOGE to increase balance enough to withdraw:
image

Still unable to withdraw after receiving 1 DOGE more than required:
image

Sent whole DOGE balance to the address it wants money in:
image

Funds received into the same account:
image

UI now happy:
image

**Comment by gomesalexandre** [comment]
> Ok there's something definitely weird going on with the checks here. I actually transferred slightly more than recommended amount and tried to withdraw and it would no let me withdraw because it didnt see the new balance.

That isn't exactly true. The new balance *is* reflected, hence why you're getting a different amount needed to be sent. That's because you now have a different UTXO set.

This is classic a classic UTXO fees estimation "issue" - we estimate fees on the original UTXO set, but then after sending funds, we estimate for the new UTXO set which yields different fee estimation.

i.e when my UTXO set is originally empty (sent all funds out of that *xpub*), Tx fee would be 22000000 but after sending the DOGE I was advised to to the *address*, the Tx fee is now 113000000, ~5x more. Still a very small amount however, ~0.22 DOGE vs. ~1.13 DOGE

Don't think there's a definitive solution around this as the helper here is used for UTXO reconciliation around lending/savers domain, and our reconciliation assumes full balance being sent to that address, so wouldn't be affected by that issue, but adding a buffer there would surely produce bugs.
Also if we were to buffer the fees, 5x would obviously going to be way too much for e.g BTC.

@woodenfurniture  Since DOGE fees are generally ~1ish DOGE, and the dust amount is 1 DOGE making for a total of 2ish DOGE, I believe we could simply `BN.Max()` the recommended amount and 3 DOGE which would leave enough buffer.
Other UTXOs will still affected by the fees estimation issue, and we should probably reassess with a similar safe amount.

**Comment by gomesalexandre** [comment]
nice idea but cantdo and wontdo :(

**Pull request closed without merging**
