### PR TITLE
fix: use active swapper quote state

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

Updates swapper logic to use the trade quote for the active swapper (currently the best swapper, but soon to be "selected" swapper) at all times.

Note, this does not yet fix https://github.com/shapeshift/web/issues/4025 - coming soon in another PR.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Closes https://github.com/shapeshift/web/issues/4037

## Risk

Medium, touches swapper quote logic.

## Testing

- Confirm that the bugs in the ticket noted above are fixed by following the replication steps
- Confirm the swapper still works as expected (if the quotes and gas look right it's probably fine - no tricky account stuff here)

### Engineering

☝️ 

### Operations

☝️ 

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
technically looks great, but i am seeing 429s against `api.0x.org`, you made it too fast ser

image

it looks like we have two options

* follow their public rates limits
* apply for a key

https://docs.0x.org/0x-swap-api/advanced-topics/rate-limiting

**Comment by 0xdef1cafe** [comment]
i'm happy to merge this if you are, as it's not worse, and more fixes are coming

**Review by gomesalexandre — COMMENTED** [review]
> technically looks great, but i am seeing 429s against `api.0x.org`, you made it too fast ser

Pretty much this, from a diff standpoint this looks good and mostly brings the new vernacular in / uses `getAvailableSwappers` instead of `getTradeQuote` so from a maintainability perspective happy to get this one in, not worse, and definitely better in terms of preparing for user-chosen swapper

**Review by gomesalexandre — COMMENTED** [review]
Retested as a sanity check because swapper:

### 0x trades on Avalanche

image
image
image


### THOR swapper

- Got into a weird "Not enough DOGE to cover gas" flow when inputting an amount, then clicking max

image

Interestingly, clicking max again does make the error state go away and give a max amount similar to prod. I wasn't able to reproduce this one after a reload and on LTC, so unless you can reproduce this one, happy to get this one in

image

#### Status step looks good

image
image

**Review by gomesalexandre — APPROVED** [review]

**Pull request merged**
