### PR TITLE
fix: qr code not filling address input

### LINKED ISSUE #2006: QR Scanner Broken In Prod
### Overview

when scanning a QR code from app.shapeshift.com, it recognizes the QR code but doesn't populate the address that's scanned. 

It broke during the v1.28 release. That Release is linked here. https://github.com/shapeshift/web/pull/1987

Triage Thread here https://discord.com/channels/554694662431178782/984524245658894336

### References and additional details

recreation steps 

1: connect the wallet to app.shapeshift.com
2: go to an asset page and click send
3: in the address send bar, click on the QR scanner
4: Scan a valid QR Code
5: yield no address populated

### Acceptance Criteria

For the QR Scanner to function properly again. 

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by GMSteuart**
## Description

- Fixes the address input not filling after a user scans a QR code

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #2006

## Risk

None, this just changes setting the field value to `SendFormFields.Input` vs. `SendFormFields.Address` previously following #1948, to match the new input to address logic, including validation

## Testing

Tested with ENS, Unstoppable Domains, Trust Wallet and MetaMask mobile (broken but irrelevant to this diff, see https://github.com/shapeshift/web/issues/2059)

- Sends should show no regressions on ETH/ERC20s/BTC and ATOM sends (to an address or to an ENS/Unstoppable domain)

1. Select asset
2. Send
3. Click QR code
4. Scan an address' QR code
5. Voila!

## Screenshots (redacted to zero address)

MetaMask Mobile:

image

Trust Wallet:

image

Unstoppable Domains:

image

ENS:

image

### CODE REVIEW

**Comment by GMSteuart** [comment]
@0xdef1cafe I made this a draft primarily because I need to double check this doesn't affect anything with the other changes you made in PR #1948.

**Review by gomesalexandre — CHANGES_REQUESTED** [review]
@GMSteuart That fixes the QR code being filled in the input, but breaks 0x addresses/ENS/Unstoppable Domains (it is now impossible to type any char in the input field, since it is now controlled by the `SendFormFields.Address` field).

For context, https://github.com/shapeshift/web/pull/1948/ now separates the notions of an `Input` (the raw input, user-input or QR-code scanned in this case) and `Address` (the actual address used for making the Tx) in send form input fields.

This diff fixes it, by reverting the `<AddressInput />`'s `<Input />` component to be a `SendFormFields.Input`:

```diff
diff --git a/src/components/Modals/Send/AddressInput/AddressInput.tsx b/src/components/Modals/Send/AddressInput/AddressInput.tsx
index 044c0015..dffb2512 100644
--- a/src/components/Modals/Send/AddressInput/AddressInput.tsx
+++ b/src/components/Modals/Send/AddressInput/AddressInput.tsx
@@ -37,7 +37,7 @@ export const AddressInput = ({ rules }: AddressInputProps) => {
           />
         )}
         control={control}
-        name={SendFormFields.Address}
+        name={SendFormFields.Input}
         rules={rules}
       />
       <InputRightElement>
diff --git a/src/components/Modals/Send/views/QrCodeScanner.tsx b/src/components/Modals/Send/views/QrCodeScanner.tsx
index 1337b7da..9133af25 100644
--- a/src/components/Modals/Send/views/QrCodeScanner.tsx
+++ b/src/components/Modals/Send/views/QrCodeScanner.tsx
@@ -34,6 +34,7 @@ export const QrCodeScanner = () => {
 
   const handleScan = (value: string | null) => {
     if (value) {
+      setValue(SendFormFields.Input, value)
       setValue(SendFormFields.Address, value)
       history.push(SendRoutes.Address)
     }
```

I tested it with QR codes from:

- Trust (working)
- Portis (working)
- MetaMask Mobile (not working, but irrelevant to this diff, we should tackle it in a separate issue, the address format used by MM is not a regular address but `ethereum:address@1` which is following the [EIP-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) URL format spec

**Comment by GMSteuart** [comment]
@gomesalexandre thanks for the additional testing. @0xdef1cafe confirmed that the minimal change I made would introduce breaking changes to the changes he had made.

What is the intended difference between `SendFormFields.Input` and `SendFormFields.Address`?

**Comment by gomesalexandre** [comment]
> @gomesalexandre thanks for the additional testing. @0xdef1cafe confirmed that the minimal change I made would introduce breaking changes to the changes he had made.
> 
> What is the intended difference between `SendFormFields.Input` and `SendFormFields.Address`?

Input is the raw input and Address is the parsed input e.g an address from an ENS or an Unstoppable Domain

**Review by 0xdef1cafe — APPROVED** [review]
tested working with qr, regular, and vanity addresses for btc/eth

**Review by gomesalexandre — APPROVED** [review]
Self-🍬

**Pull request merged**
