### PR TITLE
feat: turn thorchain lending on

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Turns THORChain lending on.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

- This turns THORChain lending on, so lending should obviously be happy

## Testing

- Do a final sanity check of THORChain lending before this goes in

### Engineering

None, already tested by ops

### Operations

- ☝🏽

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #5827** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5827?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5827?utm_source=stack-comment).

**Comment by 0xean** [comment]
@gomesalexandre - just to confirm, there are no fees on lending at the moment?

**Comment by gomesalexandre** [comment]
> @gomesalexandre - just to confirm, there are no fees on lending at the moment?

That's correct @0xean - we *could* bring them in in the future, but can't do that at the moment as THOR endpoints don't support affiliate bps for lending, see https://github.com/shapeshift/web/pull/5813

**Comment by 0xean** [comment]
perfect, thanks, was just talking with Tim and he asked me to confirm.

**Review by 0xApotheosis — APPROVED** [review]
🚀

**Pull request merged**
