### PR TITLE
chore: use mocked from jest-mock in tests

### LINKED ISSUE #1293: Fix log spew
### Overview

**Reserved for @0xf11nix - do not apply for this bounty**

We have a bunch of log spew in CI from jest and it's heaps gross aye.

### References and additional details

Check an existing CI run for an example

https://github.com/shapeshift/web/runs/5681039565?check_suite_focus=true

### Acceptance Criteria

* `yarn test` runs without any rank log spew

### Need By Date

N/A

### Screenshots/Mockups

_No response_

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Sponsor / Stakeholder

@0xdef1cafe

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

### PR DESCRIPTION
**Pull request by 0xf11nix**
## Description

This PR migrates the deprecated `mocked` test helper from `ts-jest/utils` to the suggested replacement from `jest-mock` in order to fix the large number of deprecation warnings, etc, being generated when running `yarn test`.

Most of the output refers to a single [deprecation warning](https://github.com/facebook/jest/pull/12089).
Documentation related to the source of this warning can be found in the [ts-jest guides](https://github.com/kulshekhar/ts-jest/blob/39c103f0602385a60bd4308359acab6070799a90/website/versioned_docs/version-27.1/guides/test-helpers.md)

I have added `jest-mock` as a devDependency in `package.json`, but since it is already a dependency of a number of existing packages, it does not actually result in changes to the yarn.lock file.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Closes #1293 

## Risk

There is some potential risk of regression in the testing environment, though all existing test are passing, so I would expect this risk to be fairly low at this point in time.

Since this is a dev/test dependency only, the possibility of this change affecting the production environment seems highly unlikely.

## Testing

run `yarn test` and observe the lack of rank spew (example in screenshot below)

## Screenshots (if applicable)
yarn-test-output

### CODE REVIEW

**Review by 0xApotheosis — APPROVED** [review]
Tested: does what it says on the tin, nice one.

I'll leave it to your discretion after you speak with @cjthompson about whether we should kill the `ts-jest` dependency, or if it's needed for jest tests in some way we haven't thought of - comment your learnings before merging 👌

**Review by gomesalexandre — APPROVED** [review]
LGTM @0xf11nix! Tested locally and this removes the log spew.

As @0xApotheosis mentioned, it looks like `ts-jest` dependency should be able to go away. It's not used anywhere, isn't even present in `yarn.lock` as a transient dependency of any package, and `yarn local-ci` runs without any issue without it but please double-check before we merge this.

**Comment by 0xf11nix** [comment]
Thank you for you reviews @0xApotheosis and @gomesalexandre.

Yes, `ts-jest` is a weird one. While it has been, for some time, considered the standard (and required) preprocessor for Typescript in Jest, Jest@24 changes the game slightly. While there does still seem to be some uncertainty about both the future of this this package and it's relevance ([see here](https://github.com/kulshekhar/ts-jest/issues/961)), our current configurations, mostly the TS build and lint pipelines, mean we seem to be adequately covered for type-checking with or without this dependency, at this point in time. 

The removal of `ts-jest` would slightly increase the chance that we may see some regression or unexpected behavior within the test env when making changes to seemingly unrelated dependencies, such as core TS/tsc, babel/babel plugins, or even jest, itself.

While this dependency has been in the codebase since initial commit, and its (now) deprecated test helpers have only actually been referenced in tests since #606, I do think it's probably reasonable to remove it.

There is still seems to be some uncertainty about where (if anywhere) `ts-jest` is heading, but while our tests are passing, and type-checking as expected, we can probably afford to wear the very slight risk of potential short term consequences. 

Short term? Well, yes. -ish. I would expect that there will be somewhat of a backoff in risk as TS support in both core Jest and the Babel transpiler improves. Until then, we'll kind of just need to keep an eye on it.

Bonus: One less "unmet peer dependency" warning on install

**Comment by gomesalexandre** [comment]
> There is still seems to be some uncertainty about where (if anywhere) `ts-jest` is heading, but while our tests are passing, and type-checking as expected, we can probably afford to wear the very slight risk of potential short term consequences.
> 
> Bonus: One less "unmet peer dependency" warning on install

Thanks for the detailed comment! Agreed, the risk is very low compared to having an unused dependency in `package.json`, we will not likely not meet any issue. Waiting for @cjthompson green light on this one before this is merged, but I agree with the rationale and everything works as intended locally so well done @0xf11nix !

**Review by gomesalexandre — APPROVED** [review]

**Pull request merged**
