### PR TITLE
feat: add tallyho wallet

### PR DESCRIPTION
**Pull request by 0xzoz**
## Description

Add Tally Ho wallet as an option to connect via desktop browsers. 

## Notice

- [X] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [X] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

- Adds Tally Ho wallet as an option
- Restricts Tally Ho on Mobile due to incompatibility
- Introduces mobileEnabled flag within WalletProvider individual Wallet configs

## Testing

`yarn lint`
`yarn test`

## Screenshots (if applicable)

**Desktop view**

Screen Shot 2022-05-13 at 4 06 48 PM

Screen Shot 2022-05-13 at 4 09 10 PM

Screen Shot 2022-05-13 at 4 16 22 PM

**Mobile view**

Screen Shot 2022-05-13 at 4 04 51 PM

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
hey @0xzoz gave this a quick test, will comment with a few bugs as i go

image

wallet does not work at all in this state, it must be the default provider

**Comment by 0xdef1cafe** [comment]
with metamask extension disabled, and tally ho enabled, and set as default wallet, i was able to connect and it works as expected, tested sending a tx

**Comment by 0xdef1cafe** [comment]
this does not work with the metamask extension enabled - we'll need to more gracefully handle how we're detecting the ethereum provider. we may need to make a change in hdwallet.

what does the `window.ethereum.isTally` denote - why do we need to treat the tally provider differently than metamask?

**Comment by 0xzoz** [comment]
Yes @0xdef1cafe these items come up a lot when integrating into different protocols. I've found it depends on how the dev team wants both MM and Tally Ho to interact with each other and was going to ask how Shapeshift would like it done. The cases are:

These are the four cases that usually cause issues and how it is being done in some cases. 1 and 4 are usually ok and 2 and 3 :

1. User has both MM and Tally Ho installed, Tally Ho is set to default and clicks the button to use Tally Ho
       - Connects to Tally Ho with no issues
2. User has both MM and Tally Ho installed, Tally Ho is set to default and  clicks the button to use MM
       - Gets warning that Tally Ho is installed and set to default
3. User has both MM and Tally Ho installed, Tally Ho is set not to default and clicks the button to use Tally Ho
       - Gets warning telling the user to either install Tally or set it to Default
4. User has both MM and Tally Ho installed, Tally Ho is set not to default and clicks the button to use MM
       - Connects to MM with no issues

These are usually ok and the user will get sent to the extension download page:

- User has only MM installed and clicks Tally
- User has only Tally Ho installed and clicks MM

There could be additional changes in HdWallet that may help with the cases above, like in your comment above. I can do some changes to address this but if you or others from the team have a specific way you would like this handled I'm happy to assist.

**Comment by 0xzoz** [comment]
`window.ethereum.isTally` is to recognize that Tally is being injected and helps with handling the above cases.

**Comment by 0xzoz** [comment]
> How can we make it work just like switching between any other wallet? Unfortunately, this "set as default" setting harms the user experience, for both MM and Tally. If someone clicks Tally - they should get Tally (even if it's not set as default). It needs to open the wallet instead of taking the user to the extension store. I feel like there should be a way to solve this.

@DiggyDiggy2 yeah, I agree. I can propose the following changes that can address your concerns.

**Case:** User has both MM and Tally Ho installed, Tally Ho is set to default and clicks the button to use MM

The user gets a warning and cannot connect

Screen Shot 2022-05-19 at 12 04 06 PM

**Case:** User has both MM and Tally Ho installed, Tally Ho is set not to default and clicks the button to use Tally Ho

The user gets a warning and cannot connect


Screen Shot 2022-05-19 at 12 11 39 PM

**Comment by 0xdef1cafe** [comment]
> > How can we make it work just like switching between any other wallet? Unfortunately, this "set as default" setting harms the user experience, for both MM and Tally. If someone clicks Tally - they should get Tally (even if it's not set as default). It needs to open the wallet instead of taking the user to the extension store. I feel like there should be a way to solve this.
> 
> @DiggyDiggy2 yeah, I agree. I can propose the following changes that can address your concerns.
> 
> **Case:** User has both MM and Tally Ho installed, Tally Ho is set to default and clicks the button to use MM
> 
> The user gets a warning and cannot connect
> 
> Screen Shot 2022-05-19 at 12 04 06 PM
> 
> **Case:** User has both MM and Tally Ho installed, Tally Ho is set not to default and clicks the button to use Tally Ho
> 
> The user gets a warning and cannot connect
> 
> Screen Shot 2022-05-19 at 12 11 39 PM

@shapeshift/product what do you think of the above?

**Comment by reallybeard** [comment]
This looks great! The copy is well written. Cheers! I like it.

**Comment by 0xdef1cafe** [comment]
> This looks great! The copy is well written. Cheers! I like it.

awesome, ty @reallybeard and @willyogo per https://discord.com/channels/554694662431178782/876915650235363388/978712344630792263

@0xzoz let's proceed with your suggested changes plz!

**Comment by 0xzoz** [comment]
> @0xzoz let's proceed with your suggested changes plz!

Awesome @0xdef1cafe. Changes implemented, tested locally and pushed with [0daaa82](https://github.com/shapeshift/web/pull/1790/commits/0daaa825b15f729137a5333710776749760824d5)

**Comment by 0xdef1cafe** [comment]
@shapeshift/operations can you please backread the conversation and above and test as per @0xzoz changes? ty :)

**Comment by MBMaria** [comment]
When logged into MM and it is the default, for a smooth transition to TallyHo, after you select TallyHo to be the default, I found it best to disconnect the MM wallet. Even though you can switch directly from the MM to TallyHo (after default has been changed) if you hit refresh then the site will keep opening the MM extension in the settings page in the browser (tested in Chrome) until TallyHo is taken off default (and vice versa). Perhaps some additional copy in the connect wallet menu to disconnect MM before switching wallets might be more seamless?

**Comment by MBMaria** [comment]
Just FYI I installed TallyHo! to test this. I have then closed out of the fleek build and attempting to connect MM in app.shapeshift it comes up with this message.
image

TallyHo is not set as my default wallet and I am currently logged into MM.

I removed TallyHo from my extensions and was able to reconnect to MM.

**Comment by 0xzoz** [comment]
> Just FYI I installed TallyHo! to test this. I have then closed out of the fleek build and attempting to connect MM in app.shapeshift it comes up with this message. image
> 
> TallyHo is not set as my default wallet and I am currently logged into MM.
> 
> I removed TallyHo from my extensions and was able to reconnect to MM.

Thanks for catching this @MBMaria, I've added a fix in the most recent commit.

**Review by 0xdef1cafe — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Review by theoboldfrazier — APPROVED** [review]

**Pull request merged**
