### PR TITLE
chore: release v1.514.0

### PR DESCRIPTION
**Pull request by 0xApotheosis**
feat: add basic components for pool (#5973)
fix: add pool icon (#5972)
feat: thorchain LP flag and route (#5966)
feat: non native assets max swaps (#5961)
fix: revert donations bandaid for 0x, 1inch, and LiFi (#5963)
feat: bump axios and migrate  to axios-cache-interceptor (#5943)
fix: lock axios to older, none esm version (#5980)

### CODE REVIEW

**Comment by MBMaria** [comment]
Trade/approval borked on 1inch and Lifi
image

**Comment by MBMaria** [comment]
Blocker:

- [ ] Lifi/1inch trades/approvals borked
image

**Comment by MBMaria** [comment]
Non blocker 

- [ ] feat: thorchain LP flag and route (https://github.com/shapeshift/web/pull/5966) - toggling the flag on does not show "Pools" in the side menu

**Comment by MBMaria** [comment]
Discord testing thread: https://discord.com/channels/554694662431178782/1194774501238505532

**Comment by 0xApotheosis** [comment]
> Non blocker
> 
> * [ ]  feat: thorchain LP flag and route ([feat: thorchain LP flag and route #5966](https://github.com/shapeshift/web/pull/5966)) - toggling the flag on does not show "Pools" in the side menu

I suspect that's one of those hot reload issues - it works when setting the flag before build, but can't be changed after the fact.

**Pull request merged**
