### PR TITLE
fix: walletconnect dapps listing and scraping script

### LINKED ISSUE #3833: Oudated WalletConnect dApps listing and scraping script broken
### Overview

The WalletConnect dApps listing is outdated/incorrect (two apps I've tried had oudated URLs, which remain outdated in the official WalletConnect registry... but it doesn't mean we can't correct them on our side). We want it to be updated for our users.

Furthermore the script previously used to scrape data (more so import data as it was already a JSON file) from WalletConnect's official registry for dApps isn't working anymore.

### References and additional details

Scraping script to update: `scripts/scrapeWalletConnectRegistry.ts`
Cached registry we use for dApps: `src/plugins/walletConnectToDapps/registry.json`

The WalletConnect Cloud API for dApps listing is located here: https://github.com/WalletConnect/walletconnect-docs/blob/main/docs/cloud/explorer.md

### Acceptance Criteria

- Working scraping script to import the data easily.
- WalletConnect dApps listing refreshed with recent data.
- Fix two URLs for Zapper and SnapShot in the new listing.

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by firebomb1**
## Description

- Updates the `yarn scrape-walletconnect-dapps` script to use the WalletConnect Cloud API properly. Everything is requested in one `fetch` now. Re-using the `projectID` I've found in image URLs of the `registry.json` file we had generated. We continue to import all entries except the one with the `app_type` "wallet" as we do not want to list other wallets.
- Updates the `registry.json` with fresh data from WalletConnect.
- Manually fixes two URL we know are outdated in the source data: Zapper and SnapShot.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #3833

## Risk

None.

## Testing

Check the listing of dApps for WalletConnect. Verify also 2 specific entries, Zapper and SnapShot, they should have working URLs without redirect.

### Engineering
☝️ 

### Operations
☝️

### CODE REVIEW

**Comment by firebomb1** [comment]
Just an odd, maybe unrelated, thing happened after running `yarn` to update the dependencies.

While I was working on the script which uses `node-fetch`, I had no issue running the script... but after running `yarn` before making this into a PR, I was able to run the script anymore, it always produced this error:

```bash
scripts/scrapeWalletConnectRegistry.ts:2:19 - error TS7016: Could not find a declaration file for module 'node-fetch'. '/home/user/dev/shapeshift/web/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';
```

I had to use `npm i --save-dev @types/node-fetch`, and even had to use `--force` to finally make it work. I did not commit the changes that it would imply on the package.json/lock and yarn.lock, but it seems there might be a dependency issue somewhere. I've also tried to remove the whole `node_modules` directory and run `yarn` before this, but the error above was still happening 🤔

**Comment by 0xdef1cafe** [comment]
thanks @firebomb1 - i added those types back as a dev dependency. i recently ran a tool over the repo and ripped out a bunch of unused stuff, i couldn't see where those types were used at all, but happy to readd them especially as a dev dep that isn't included into the build.

ran the script locally, much faster, and got the same diff output as you (minus the two manually fixed assets).

ideally we'd have an `overrides.json` type thing we can merge over the top.

**Comment by 0xdef1cafe** [comment]
@firebomb1 i went ahead and added a list of maintained overrides, instead of manually editing the script output - the next person that does this won't know to manually edit zapper and snapshot, but they can read overrides.

**Comment by 0xdef1cafe** [comment]
@firebomb1 if you want to check my work by pulling the branch and running the script against to confirm no change in output, happy to merge this.

**Comment by firebomb1** [comment]
Works perfectly, great addition! Thanks!

**Pull request merged**
