### PR TITLE
feat: export and use Nullable<T> type in multi-account featureset

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Convenience end-of-stack PR that moves the existing `Nullable<T>` type away from `useRefCallback` into `types/common`, and consumes it across the multi-account featureset as a convenience type.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

None, this is only a type system change, if tsc is happy, we are happy 

### Engineering

- `yarn type-check` is happy

### Operations

- None, no runtime change

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
          * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
            * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2642** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2642" target="_blank">Graphite</a> 
    * **PR #2644** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2644" target="_blank">Graphite</a> 
      * **PR #2651** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2651" target="_blank">Graphite</a> 
        * **PR #2652** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2652" target="_blank">Graphite</a> 
        * **PR #2661** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2661" target="_blank">Graphite</a> 
          * **PR #2680** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2680" target="_blank">Graphite</a> 
          * **PR #2669** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2669" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2669?utm_source=stack-comment).

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xApotheosis** [comment]
@gomesalexandre I think this guy needs to be re-stacked to fix the diff and merge conflicts.

**Comment by gomesalexandre** [comment]
> @gomesalexandre I think this guy needs to be re-stacked to fix the diff and merge conflicts.

Looks like https://github.com/shapeshift/web/pull/2691 which got in before rugged this one with many conflicts, thankfully they were all quite straightforward, all mergefixed

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
