### PR TITLE
perf: don't render closed modals

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
## Description

don't render closed modals to the dom and compute things eagerly in the background

we lose the modal closing animation as a result, but @reallybeard is ok with this

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

n/a - things are slow

## Risk

minimal

### Engineering

as discussed with @woodenfurniture

### Operations

see that modals work as expected

## Screenshots (if applicable)

no visual change, except no modal close animation

### CODE REVIEW

**Comment by woodenfurniture** [comment]
fox ops page broken ser. I'll try fix now otherwise failing that we may need to adjust approach

image

image

**Comment by woodenfurniture** [comment]
Ok the error message above can be resolved with this change 

```
diff --git a/src/plugins/foxPage/foxPage.tsx b/src/plugins/foxPage/foxPage.tsx
index b26e7781d..c6f14d674 100644
--- a/src/plugins/foxPage/foxPage.tsx
+++ b/src/plugins/foxPage/foxPage.tsx
@@ -104,7 +104,7 @@ export const FoxPage = () => {
     [activeAssetId, assets],
   )
 
-  const selectedAsset = assets[selectedAssetIndex]
+  const selectedAsset = assets[selectedAssetIndex] ?? assetFox
 
   const foxFilter = useMemo(() => ({ assetId: foxAssetId }), [])
   const foxyFilter = useMemo(() => ({ assetId: foxyAssetId }), [])

```

but the opportunities page will stay blank until all network fetches are complete, which take ~10-30s on local. We'll need to refactor the loading state of this page before we can merge this. Alternatively we could add this to your change:

```
return Modal.isOpen && key !== 'opportunities' && <Modal.Component key={key} {...Modal.props} />
```

**Review by woodenfurniture — CHANGES_REQUESTED** [review]
pls see comments ser

**Comment by 0xApotheosis** [comment]
Giving a testeroony now.

**Review by 0xApotheosis — APPROVED** [review]
gm sers

**Pull request merged**
