### PR TITLE
feat: reduce redundant caches in github actions

### LINKED ISSUE #1104: Reduce Cypress run-time in CI
### Overview

In `web`'s CI pipeline we have two workflow files that trigger runs when a PR is made against `main`, `develop`, or `releases/**`: 

1. `.github/workflows/pr.yml`
2. `.github/workflows/pr-cypress.yml`.

In each workflow, we use `actions/cache@v2` to cache our node modules, so we only run `yarn install --frozen-lockfile` when we have a cache miss.

The current implementation has a number of inefficiencies:

- If we have a cache miss on the node modules, we rebuild the node modules on each worker. There is currently one worker assigned to `pr.yml`, and 3 assigned to `pr-cypress` - so we do this 4 times, when 1 would suffice. We could instead implement a discrete build step, that all workers will wait on, instead of each worker rebuilding their own.
- Similarly, within the Cypress runner we have a `Cache Cypress binary` step, which again, in the event of a cache miss, runs once on each of the 3 workers.

Something like `actions/upload-artifact@v2` and `actions/download-artifact@v2` might be of use here - please reach out to @0xdef1cafe once you've identified a path forward with a request to whitelist any actions that need to be enabled in the `web` repo.

### Reference

Current workflow examples:

1. The [`Run Cypress` workflow](https://github.com/shapeshift/web/runs/5397865933?check_suite_focus=true)
2. The [`commitlint-lint-typecheck-test-build` workflow](https://github.com/shapeshift/web/actions/runs/1924944022)

### Acceptance Criteria

Reduce our total CI worker time by implementing discrete build steps for both Node and Cypress binaries.

Concretely, this would look something like:

1. A discrete step that replaces `Cache dependencies` in `pr.yml`, and `Cache central yarn modules` in `pr-cypress.yml`, and is waited on
2. A step that replaces `Cache Cypress binary` in `pr-cypress.yml`, and is waited on

Each of these steps should run at most each time the CI workflow is triggered.

Note, there is no expectation to reduce the _duration_ of the CI process (though it'd be a welcome bonus!) - only the total worker time used each time CI is triggered.

### Screenshots/Mockups

_No response_

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Before merging, please read this

Note from @0xApotheosis: as our workflow names have changed with the introduction of an initial bootstrap workflow, we (@0xdef1cafe) will need to update the required checks accordingly. 

To mitigate the risk of blocking other `web` PRs, we should update this as close to merge time as possible - a dummy PR should then be created to triple check there are no teething issues.

## Description

This PR adds a `bootstrap` workflow that installs and caches all required files so that in `pr` and `pr-cypress` workflow the dependencies are not needed to be installed again.

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1104

### CODE REVIEW

**Review by 0xApotheosis — COMMENTED** [review]
Nice one @Soptq - this looks good on the node front.

Cypress is still rebuilding the binary, even on a cache hit. I suspect we need to update the configuration of `cypress-io/github-action@v2` to handle this.

Something like the below might give us what we need:

```yml
with:
  install: false
```

**Comment by 0xApotheosis** [comment]
@Soptq if there was a cache miss on our build files, would we end up running `Cache build folder` in both `pr` and `pr-cypress` workflows, as we've defined this workflow in each of them?

Or will there never be a cache miss because we are running `Cache build folder` in our bootstrap workflow beforehand?
And if that's the case, do we actually need to run `Cache build folder` in `pr` and `pr-cypress` workflows?

**Comment by Soptq** [comment]
> @Soptq if there was a cache miss on our build files, would we end up running `Cache build folder` in both `pr` and `pr-cypress` workflows, as we've defined this workflow in each of them?
> 
> Or will there never be a cache miss because we are running `Cache build folder` in our bootstrap workflow beforehand? And if that's the case, do we actually need to run `Cache build folder` in `pr` and `pr-cypress` workflows?

Oh I get your concern. I think currently our github actions can ensure the pr and pr-cypress can always hit the build cache, because the install-and-cache job is guaranteed to be executed before pr and pr-cypress (if build is failed, the install-and-cache job will directly return error). However, since pr and pr-cypress are two standalone workflows (i.e. they are executed in different runners and environments), the built app in install-and-cache job cannot be directly used by them. That's the reason why we use Cache build folder in pr and pr-cypress, mainly to fetch cached files.

**Comment by 0xApotheosis** [comment]
I can't approve this, because I created it - but I consider this good to go ✅ 

We've reduced total build time by over 30%, well done @Soptq! 🥳

**Review by cjthompson — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
