### PR TITLE
chore: update pull request template

### PR DESCRIPTION
**Pull request by Neverwas-dev**
## Description

Please describe your changes

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

### CODE REVIEW

**Review by 0xean — APPROVED** [review]

**Comment by Neverwas-dev** [comment]
Removed unnecessary line " Do all new and existing tests pass? Does the linter pass?"

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
two things:

1. can you please rename your pr to `chore: update pull request template` - i don't think commitlint likes underscores or caps and needs to start with a conventional commit prefix. do `git commit --allow-empty -m "chore: trigger ci" && git push` after to make ci run again
2. do you want to make another PR to make `Have you followed the guidelines in our Contributing guide?` link to our contributing guidelines?

**Comment by Neverwas-dev** [comment]
> two things:
> 
> 1. can you please rename your pr to `chore: update pull request template` - i don't think commitlint likes underscores or caps and needs to start with a conventional commit prefix. do `git commit --allow-empty -m "chore: trigger ci" && git push` after to make ci run again
> 2. do you want to make another PR to make `Have you followed the guidelines in our Contributing guide?` link to our contributing guidelines?

1. Is done as asked
2. Is the following incorrect and if so what is the new link you are requesting? https://github.com/shapeshift/web/CONTRIBUTING.md

**Comment by 0xdef1cafe** [comment]
> 

that's the right file, but your link 404's, i think you want https://github.com/shapeshift/web/blob/main/CONTRIBUTING.md

that doc is looking a little sad, we might want to update that and then link to it in the template in a second PR. let's just merge this one now.

**Pull request merged**
