### PR TITLE
fix: redirect keepkey users if they accidentally exit the wipe modal

### LINKED ISSUE #1610: Gracefully handle not completing the KeepKey initialization flow
### Overview

The user can select the close or back buttons to exit the initialization flow, possibly by accident. This will drop them into a broken state until they choose to disconnect their wallet. This may be a non-obvious fix, especially if the user got into the state accidentally.

165401124-20b3d3ed-632a-41c6-a086-dbdc6bbf3495

### References and additional details

We'll want to update the `onClose()` model handler (and any other relevant handlers) to ensure the app is left in a happy state.

### Acceptance Criteria

If a user disconnects their KeepKey close the modal and kick them back to the connect wallet flow. Also, send the user to the wallet connection screen if they ever close (x) out of the recovery modal.

Product to confirm.

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by jmurphy5613**
…cess

## Description

I added a check in WalletViewsSwitch.tsx that redirects Keeykey users to the main page if they exit the modal. Instead of the app being in a broken state where it appears that they are connected with a keepkey, they can re-enter the connect wallet process.

This does not redirect users after a successful wipe setup. 

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

fixes #1610

## Risk

None

## Testing

Connect a wiped Keepkey, and enter the connect wallet flow. Then try to close the modal during the set up process.

### CODE REVIEW

**Comment by 0xApotheosis** [comment]
Hi @jmurphy5613.

Thanks for your contribution, however for bounties we only accept contributions once you've been approved for the task: https://app.dework.xyz/shapeshift-dao/keepkey-bounties?taskId=1546ffaa-5a94-4409-8546-d6e892e8cd90

**Comment by jmurphy5613** [comment]
> Hi @jmurphy5613.
> 
> Thanks for your contribution, however for bounties we only accept contributions once you've been approved for the task: https://app.dework.xyz/shapeshift-dao/keepkey-bounties?taskId=1546ffaa-5a94-4409-8546-d6e892e8cd90

I am approved for this task. I think you may be looking at the bounty.

**Comment by BitHighlander** [comment]
*updated the dwork. This is a @Cosmic on discord  https://app.dework.xyz/shapeshift-dao/keepkey-bounties/overview?taskId=85103378-5099-4435-a609-0cd3540ad601

**Comment by 0xApotheosis** [comment]
> *updated the dwork. This is a @cosmic on discord https://app.dework.xyz/shapeshift-dao/keepkey-bounties/overview?taskId=85103378-5099-4435-a609-0cd3540ad601

Got it, ty @BitHighlander - re-opening.

**Comment by 0xdef1cafe** [comment]
@jmurphy5613 do you own a keepkey?

**Comment by jmurphy5613** [comment]
> @jmurphy5613 do you own a keepkey?

yep

**Comment by 0xdef1cafe** [comment]
converting to draft. please fix lint errors and run `yarn local-ci` on your machine and fix all issues before pushing.

**Pull request closed without merging**
