### PR TITLE
fix: filter out wallets from dapp list

### PR DESCRIPTION
**Pull request by reallybeard**
## Description

We wanted to filter out all the listings that are wallets

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

n/a

### Engineering

n/a

### Operations

With the `WalletConnectToDapps` flag on go to the dapps page and you should see a listing without wallets. 

## Screenshots (if applicable)
Screen Shot 2022-10-17 at 3 05 25 PM

### CODE REVIEW

**Review by gomesalexandre — APPROVED** [review]
Untested but if tsc is happy with this I'm happy

**Review by 0xdef1cafe — CHANGES_REQUESTED** [review]
can you rerun the generation script plz?

**Comment by gomesalexandre** [comment]
@reallybeard The reason why the JSON was invalid is because the UUID/CID or whatever the `https://explorer.walletconnect.com/_next/data/<id>/index.json?search=` param is has changed on remote and we were grabbing the 404 HTML instead of the JSON:

image

Grabbed the ID again from explorer.walletconnect.com requests which gives us a response with actual JSON data again:

image

Updated in 83fa5130c29684228a324e0c1242d60d182a51e0

**Review by gomesalexandre — APPROVED** [review]
Re-ran generation script and confirmed `wallet` category entities are filtered out, see e.g https://github.com/shapeshift/web/pull/3082/commits/074f7ef855a83ece739ab242e99c3c98a07758df#diff-602c18499dbe2c620f289dce0334193c187d55c89a119ab6ad66bda79fb8e41eL93-L98

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
