### PR TITLE
fix: only use infura for FOXy requests

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
## Description

we're hitting infura rate limits.

FOXy rebase history requires access to a full archival node

infura provides an archival node but our hosted node is not an archival node

this PR points the FOXy singleton at the infura node, and switches all other calls to ethereum nodes to our node 

* add a new `REACT_APP_ETHEREUM_INFURA_URL` config variable
* instantiate FOXy singleton with infura node
* change `REACT_APP_ETHEREUM_NODE_URL` to our hosted node

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

n/a - production issue w/ rate limiting

## Risk

* we knock our node over with the traffic
* our node can't answer certain requests

### Engineering

* **ensure i've setup each environment correctly - this won't fail until we deploy to prod** - run `yarn env <environment>` locally and verify the output is sane
* ensure FOXy requests are still going to infura
* all other eth node traffic should be going to our endpoints, which are
  `daemon.ethereum.shapeshift.com` (with `-dev` prepended for `develop.shapeshift.com` and locally)

### Operations

* shit should work again

## Screenshots (if applicable)

💩

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
```
➜  web git:(stop-the-bleeding) yarn env app | grep ETHEREUM
REACT_APP_ETHEREUM_INFURA_URL=https://mainnet.infura.io/v3/71acfee9f8544347a4676bd8affa26b8
REACT_APP_ETHEREUM_NODE_URL=https://daemon.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL=https://api.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_WS_URL=wss://api.ethereum.shapeshift.com
➜  web git:(stop-the-bleeding) yarn env private | grep ETHEREUM
REACT_APP_ETHEREUM_INFURA_URL=https://mainnet.infura.io/v3/71acfee9f8544347a4676bd8affa26b8
REACT_APP_ETHEREUM_NODE_URL=https://daemon.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL=https://api.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_WS_URL=wss://api.ethereum.shapeshift.com
➜  web git:(stop-the-bleeding) yarn env develop | grep ETHEREUM
REACT_APP_ETHEREUM_INFURA_URL=https://mainnet.infura.io/v3/71acfee9f8544347a4676bd8affa26b8
REACT_APP_ETHEREUM_NODE_URL=https://dev-daemon.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL=https://dev-api.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_WS_URL=wss://dev-api.ethereum.shapeshift.com
➜  web git:(stop-the-bleeding) yarn env dev | grep ETHEREUM
REACT_APP_ETHEREUM_INFURA_URL=https://mainnet.infura.io/v3/71acfee9f8544347a4676bd8affa26b8
REACT_APP_ETHEREUM_NODE_URL=https://dev-daemon.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL=https://dev-api.ethereum.shapeshift.com
REACT_APP_UNCHAINED_ETHEREUM_WS_URL=wss://dev-api.ethereum.shapeshift.com
```

environment configuration for posterity

**Review by gomesalexandre — DISMISSED** [review]
Confirmed all requests are going through our node, except for FOX/FOXy asset pages and FOX page, as well as a single Infura call on dashboard load.

Also, since FOXy is never fetched in the first place and isn't available as an opportunity, it is not available in the DeFi section, which should help to stop the bleed as well

**Review by 0xApotheosis — APPROVED** [review]
Confirmed working as expected.

Routes most requests via our own node 👌

**Comment by 0xdef1cafe** [comment]
> 

unfortunately AppContext does unconditionally fetch FOXy rebase history, this needs fixing too

**Pull request closed without merging**
