### PR TITLE
fix: use feature-flagged chainIds to determine use in the app

### PR DESCRIPTION
**Pull request by woodenfurniture**
## Description

Ensures the chainIds available in the app include the feature-flagged chainIds from 

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

Fixes https://discord.com/channels/554694662431178782/1247718768558477323/1247741645886062602

Moderate risk - getting this wrong would mean its possible to interact with chains that are not toggled on (e.g base chain), but this should actually improve things rather than break them.

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

Test available chains in the app are as expected.

### Engineering

See `src/context/PluginProvider/PluginProvider.tsx` for origin of `const { supportedChains } = usePlugins()`:
image

### CODE REVIEW

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
Checked against Native wallet and Metamask. With flags on everything seems to work as expected, but I got strange behaviour when disabling flags.

E.g. I just disabled Arbitrum, which has balance for 2 assets:

Screenshot 2024-06-05 at 2 37 18 PM

Those assets still take up a place in the list, but are showing empty.

**Comment by woodenfurniture** [comment]
> Checked against Native wallet and Metamask. With flags on everything seems to work as expected, but I got strange behaviour when disabling flags.
> 
> E.g. I just disabled Arbitrum, which has balance for 2 assets:
> 
> Screenshot 2024-06-05 at 2 37 18 PM
> Those assets still take up a place in the list, but are showing empty.

May need a cache clear between toggles as the portfolio maintains them after toggling off?

**Comment by woodenfurniture** [comment]
Confirmed cache clear resolves the issue, before toggling a chain off:
image

Toggling off optimism shows blank rows, reproducing the issue reported:
image

Cache clear resolves the issue:
image

Since toggling off a whole chain is considered outside the normal user flow, its reasonable to require clearing the portfolio when toggling a chain off.

**Review by 0xApotheosis — APPROVED** [review]
Cache clear indeed!

**Pull request merged**
