### PR TITLE
fix: get correct Gas Limit

### LINKED ISSUE #1025: Sending ETH to (contract address) will give an out of gas error (Native Wallet / Keepkey)
### Overview

When sending ETH directly to a contract address from the send modal you will get an out of gas error and the TX will fail when using Native Wallet (ShapeShift Wallet or Keepkey). Failed TX: https://etherscan.io/tx/0x670880a8f8c28b6b2f25aecec184b04797f3362bb8fc973e8dea1b7b5122efbb

Recreation Steps:
1. Go to app.shapeshift.com using a native wallet or keepkey
2. Send ETH directly to a contract using the send modal (not trade) Example Address https://etherscan.io/address/0x8f5df2d1045543d2e1a4be1879cabde24b81d2b9
3. Once sent notice that the out of gas error will populate once the TX is accepted on chain

### Reference

* This probably requires looking into how we estimate gas in the [ethereum chain adapter](https://github.com/shapeshift/lib/blob/main/packages/chain-adapters/src/ethereum/EthereumChainAdapter.ts#L261), or [in unchained itself](https://github.com/shapeshift/unchained/blob/develop/node/coinstacks/ethereum/api/src/controller.ts#L203)

### Acceptance Criteria

Users should be to send directly to a contract address from the send modal with a higher gas limit and not experience an out of gas error

### Screenshots/Mockups

n/a

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### PR DESCRIPTION
**Pull request by ErvinDimitri**
## Description

There was an issue in getting the correct gas Limit for a transaction, because it was calculating while the user was still entering the amount. So to get a more accurate estimation of gas Fee, it will re-estimate the gas Fee right after the user clicks the Next button (in the send amount modal)
It is a continuation from PR: https://github.com/shapeshift/web/pull/1215 

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
[Sending ETH to (contract address) will give an out of gas error](https://github.com/shapeshift/web/issues/1025)  `closes #1025`

## Risk
If the Gas Limit is set incorrectly, or this change fails, in this case, estimate a lower gas limit, the user will end up with a failed transaction; On the other hand, if the Gas Limit is overestimated, some users will end up paying more for the fees than expected (but will still be refunded), and others who do not have sufficient funds will not be able to make the transaction.

## Testing
 To test the gas limit re-estimation, I used the debugging technique to analyse if the re-estimated gas limit was the necessary gas limit to send ETH to a smart contract

## How to replicate the issue
https://github.com/shapeshift/web/pull/1215#issuecomment-1073962042

## Screenshots (if applicable)
159281018-d7c06d7e-bf92-4997-8875-79db5adf0129

### CODE REVIEW

**Comment by 0xApotheosis** [comment]
Hey @ErvinDimitri - could you please ensure that the PR template is used and filled out?

Preferably the PR is linked to an issue that describes what this PR closes, how to replicate the issue etc.

**Comment by ErvinDimitri** [comment]
Yes, I will follow the PR's template

**Comment by ErvinDimitri** [comment]
I already made the updates on PR description to follow with the template

**Comment by 0xdef1cafe** [comment]
@ErvinDimitri please check again - go through the steps of opening a new PR, but don't actually create one. you are missing the risk and testing sections.

**Comment by 0xean** [comment]
Re-opening this PR.  @ErvinDimitri  reached out asking for some help understanding what these sections are for.  Maybe something we should add to the docs in the future.

**Review by elmutt — APPROVED** [review]

**Comment by elmutt** [comment]
lgtm

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
@ErvinDimitri I'm not convinced that this PR closes #1025, which seems related to incorrect estimated gas fees being calculated.

All this PR appears to do is call `estimateFormFees()` again when `handleNextClick` is invoked, which adds a bit of extra friction for the user, as the UI blocks waiting on this response.

`estimateFormFees()` is already called in `handleInputChange`, and so our `SendFormFields.EstimatedFees` value should already be current.

Have I misunderstood?

**Comment by ErvinDimitri** [comment]
@0xApotheosis, the `estimatedFormFees()` is currently being invoked in `handleInputChange` which means that every time the user enters a digit it will estimate the Gas Limit, but this method can lead to an issue because the Gas Limit to transfer 0 ETH to a smart contract is completely different from transferring a non-zero value to a smart contract, ending up with a failed transaction.

Here is an example of what is happening:
159281018-d7c06d7e-bf92-4997-8875-79db5adf0129

This type of situation happens when the user is typing a value that has several zeros at the beginning (Ex: 0.0007) 

So to make sure we estimate the gas limit for the correct amount entered,
re-estimate the gas limit right after the user clicks the Next button (in the send amount modal). I'm using this approach because in the moment the user clicks the Next button, we know that the value entered will not change, which means we can trust in the gas limit re-estimated.

**Comment by 0xApotheosis** [comment]
Thanks for the explanation @ErvinDimitri. 

This PR only adds an extra computation, which potentially makes the gas estimate more timely, but does not make the response any more "correct" (if it is "incorrect" to begin with).

I agree that sending zero and non-zero values to a smart contract requires different gas values, and this does appear to be captured correctly in the responses we are receiving - again, this PR does not change that in any way.

I'll close this PR for now.

**Comment by ErvinDimitri** [comment]
> Thanks for the explanation @ErvinDimitri.

Welcome @0xApotheosis 

I made a demo [here](https://drive.google.com/file/d/1aefsTsO7NHKph1-Zg6R4wCEeQtPwHCGe/view?usp=sharing), that shows that this is a valid approach, and is essential for those with a slow internet connection

**Comment by 0xApotheosis** [comment]
GM @ErvinDimitri, I appreciate your persistence on this one, and for the excellent replication video!

You've convinced me - there _does_ seem to be a bug here, but it's not the issue linked in the PR.
The bug you've found looks like an issue with the order of the responses that are returned from `getFeeData` in `EthereumChainAdapter.ts`, and how they are handled by the client.

From the example you've provided, my understanding is that the bug is caused by the responses returning out of order, and the value from the last received response (rather than the last requested response) is used in the `Confirm` component. Is that how you see it?

A better solution to this would address the root cause of the bug, which might look something like using [Axios's](https://axios-http.com/docs/cancellation) [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to drop any existing requests when a new request is made, which would prevent requests from being received out of order.

Finally, we recently [merged a PR](https://github.com/shapeshift/web/pull/1399) which fixed a debouncing issue with the send input, which may have actually mitigated the issue. Are you able to confirm if it has been fixed by that PR?

**Comment by 0xApotheosis** [comment]
@ErvinDimitri a quick update of this - I replicated your original issue, and it does seem to be fixed by https://github.com/shapeshift/web/pull/1399, as I couldn't replicate the issue once the debouncing fix was applied.

I suspect that with the debouncing now returning correctly, we send at most one request per second, which mitigates the risk of jitter muddling the order of our returned responses.

You're PR here was the only reason I stumbled across the debouncing issue in the first place, so thank you for that!

**Comment by ErvinDimitri** [comment]
> From the example you've provided, my understanding is that the bug is caused by the responses returning out of order, and the value from the last received response (rather than the last requested response) is used in the `Confirm` component. Is that how you see it?

Yes, exactly



> Are you able to confirm if it has been fixed by that PR?

I tested the code using the PR https://github.com/shapeshift/web/pull/1399/ and the bug was mitigated



> Your PR here was the only reason I stumbled across the debouncing issue in the first place, so thank you for that!

My pleasure, I learned interesting things during this PR, thanks

**Comment by 0xean** [comment]
@ErvinDimitri - tip sent your way for the efforts.

**Comment by ErvinDimitri** [comment]
Thank you so much 💪

**Pull request closed without merging**
