### PR TITLE
feat: multicurrency trade support

### LINKED ISSUE #1995: Multi currency - trade support
### Overview

Currently, the multi currency implementation does not have any consideration for trading.

### References and additional details

We need a way for the UI to display/work with non-USD currencies, without swapper having significant knowledge of the user's currency preference.

Find a minimal way for a user to be able to do trades in a foreign currency, without littering rubles into the swapper.

### Acceptance Criteria

* We can trade in foreign currencies via swapper

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

1 day

### PR DESCRIPTION
**Pull request by stackedq**
## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1995

## Risk

It's related to the trade-card, so there's a risk.

## Testing

Enable `Multicurrencies` feature flag, open up the settings modal, and change the currency to something other than USD,
Test trading.

### CODE REVIEW

**Review by elmutt — APPROVED** [review]

**Review by elmutt — CHANGES_REQUESTED** [review]
Noticed an issue with Jpy and the swapper I think:
Screen Shot 2022-07-26 at 11 01 54 AM

Should this be a tiny tiny amount? It seems wrong

**Comment by stackedq** [comment]
@elmutt Yup that totally looks wrong, would you please tell me your steps? I can't repro:
tst

**Comment by elmutt** [comment]
> @elmutt Yup that totally looks wrong, would you please tell me your steps? ~I can't repro~: tst
> 
> I was able to repro, working on it.

enter an amount in the fiat input field:
Screen Shot 2022-07-26 at 11 13 42 AM

**Comment by stackedq** [comment]
@elmutt Nice catch, would you please test again?

**Comment by elmutt** [comment]
> @elmutt Nice catch, would you please test again?

Still noticing a problem I think:
Screen Shot 2022-07-26 at 12 57 43 PM

**Comment by 0xdef1cafe** [comment]
@stackedq before you go completely insane and pull your hair out - @elmutt and i suspect there might be some underlying swapper issues causing this behavior. it might be best to try and repro this on `develop` or `main`, as swapper is constantly a moving target and lots of things have gone in recently.

the issues you are seeing may not be directly related to your implementation here, but i haven't reviewed closely yet.

**Comment by stackedq** [comment]
@0xdef1cafe Thanks for the heads up, I believe I've fixed the regression @elmutt pointed out. judging by the numbers in his screenshot, I think he put $3 into the input and changed the currency later on. my last commit will fix this issue.

**Comment by elmutt** [comment]
works great now. approved

**Review by elmutt — APPROVED** [review]

**Review by 0xdef1cafe — COMMENTED** [review]
technically LGTM, doesn't leak anywhere unnecessarily, will wait for @shapeshift/operations to test and OK before stamping

**Review by 0xdef1cafe — APPROVED** [review]

**Review by elmutt — APPROVED** [review]

**Pull request merged**
