### PR TITLE
fix: narrow smart contract wallets accounts

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

See screenshots below - the current behaviour in develop is 100% wrong and lost funds waiting to happen as we disable smart contracts safety.

Given an EVM addy that's a smart contract, it may *only* be a smart contract on one chain, not many, e.g two Gnosis safes over two EVM chains, with two diff addies:

image

Note there is only one for Avalanche and one for Ethereum here but I could just as well create as many as I want - one sc wallet requires one separate wc connection. In effect, one sc wallet connected through wcv2 will always have an account on a single chain only.

This PR fixes the current accounts derivation by bailing on all other chains if a smart contract address is found for one, making things nice and safe.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

- closes https://github.com/shapeshift/web/issues/7496

> What protocols, transaction types or contract interactions might be affected by this PR?

Theoretically very very low - only touches WCV2 as a wallet, and smart contracts addresses specifically. Though since this lives in the EVM accounts derivation utils, effectively high-risk. 

## Testing

- Create a Gnosis Safe on any chain of your liking
- Connect to said safe via WC as a wallet
- Ensure the only AccountId present is the one for your safe's chain

### Engineering

- ^

### Operations

- ^

## Screenshots (if applicable)

develop (right) vs. this diff

Screenshot 2024-08-06 at 21 43 43
Screenshot 2024-08-06 at 21 44 06

### CODE REVIEW

**Review by NeOMakinG — COMMENTED** [review]
Ethereum with WC
image

❌  Avalanche with WC using a fresh wallet

image

Any ideas why I see every assets while using a fresh avalanche safe wallet account?

**Comment by gomesalexandre** [comment]
> Any ideas why I see every assets while using a fresh avalanche safe wallet account?

@NeOMakinG just tested with a safe on Ethereum:

image

And a safe on Avalanche:

image

And both are correctly showing only one account. If you can consistently repro this with a full cache clear, happy to debug this together!

**Comment by NeOMakinG** [comment]
I have been able to reproduce:

- First connect the SC wallet on develop, wait for all accounts to load
- Checkout this branch, connect the same SC wallet, you'll see the full list loaded while this PR assume we should only load the supported chain

This is a cache issue, meaning that even if we merge and release this PR, our users might have a big list of accounts already loaded and might result in funds lost

This hasn't been introduced by this PR but we should take care of it as long as users funds could be lost

**Review by NeOMakinG — APPROVED** [review]
We can get this one in as long as we create an issue regarding the cache and think about it in a follow up

**Comment by gomesalexandre** [comment]
> I have been able to reproduce:
> 
> * First connect the SC wallet on develop, wait for all accounts to load
> * Checkout this branch, connect the same SC wallet, you'll see the full list loaded while this PR assume we should only load the supported chain
> 
> This is a cache issue, meaning that even if we merge and release this PR, our users might have a big list of accounts already loaded and might result in funds lost
> 
> This hasn't been introduced by this PR but we should take care of it as long as users funds could be lost

Very nice catch @NeOMakinG! While I originally thought this was a hollistic issue (well... it kind of is in a way) with us keeping stale accounts from other wallets, this is indeed a simple cache busting migration scenario, with the root cause laying in `<AppContext />`'s `requestedAccountIds` - another bug related to the account management follow-up and wrong reactivity we sometimes encounter. This loosely relates to https://github.com/shapeshift/web/issues/7214.

Fixed in f9ccf7b86:

- Before migration:

Screenshot 2024-08-08 at 19 12 40

- After migration

image

**Review by NeOMakinG — APPROVED** [review]
Develop
image

This branch without cache clearing (thanks to the migration)
image

Looks super fine now! Thanks for the migration making our users safer! 💜

**Pull request merged**
