### PR TITLE
fix: mission cards overflowing copies and duration locale

### PR DESCRIPTION
**Pull request by firebomb1**
## Description

Minor tweak for the Missions cards for longer copies (translations), likely better if @reallybeard checks these changes visually.

- Fixes the overflowing texts to go on multiple lines and align correctly in the Mission cards.
- Use the user's locale in `dayjs` to display the correct language for duration of ongoing missions in Mission cards.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Risk

Low. Only minor visual fixes and correct usage of the user's language for duration.

## Testing

Check the visual rendering of mission cards throughout the app in the supported languages. The should either be on a single line when the copy is short enough or span on multiple lines and not overflow above other elements if they are long.

### Engineering
☝️ 

### Operations
☝️ 

## Screenshots (if applicable)
Before (CTA in the right colum):
image

Before Missions page (problem circled in red)
image

After CTA (French)
image

After CTA (English) (same as before)
image

After Missions page (see "days" replaced by "jours" in French, tested in other languages)
image

After Missions page on Mobile
image

### CODE REVIEW

**Comment by twblack88** [comment]
oh good catch @firebomb1 did we test other languages like russian?

**Comment by firebomb1** [comment]
We did, we did :)

image

**Comment by firebomb1** [comment]
Beards visual review on Discord

**Review by gomesalexandre — APPROVED** [review]
Tested locally:

### Desktop

image
image
image

image
image
image

### Mobile

image
image

image
image

**Pull request merged**
