### PR TITLE
chore: consolidate big number helpers

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

Consolidate duplicate `bignumber` usage across the now-consolidated investor packages. There is a slight difference with the now-used `bnOrZero` helper, but it's slightly more strict, and so should operate functionally the same.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

There is a small risk that the calculations using the `bnOrZero` helper produce a different result, though for valid inputs this should not be the case.

## Testing

Investor related activities (earn, foxy etc) should function the same as it does currently.

### Engineering

☝️

### Operations

☝️

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by 0xApotheosis** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4505** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4505" target="_blank">Graphite</a> 
    * **PR #4506** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4506" target="_blank">Graphite</a> 
      * **PR #4507** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4507" target="_blank">Graphite</a> 
        * **PR #4508** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4508" target="_blank">Graphite</a> 
          * **PR #4509** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4509" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4509?utm_source=stack-comment).

**Review by woodenfurniture — DISMISSED** [review]
🐐

**Comment by 0xApotheosis** [comment]
@0xApotheosis queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4509).

**Comment by 0xApotheosis** [comment]
[Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4509) couldn't merge this pull request because a downstack PR #4507 failed to merge.

**Pull request merged**
