### PR TITLE
chore: update logging in various components

### PR DESCRIPTION
**Pull request by cjthompson**
## Description

This is an ongoing process and there will be multiple PRs.

## Notice

- [X] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [X] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A
## Risk
Low

## Testing
None

### CODE REVIEW

**Review by 0xApotheosis — APPROVED** [review]
🍭

**Comment by gomesalexandre** [comment]
Can we add testing steps to the description? I've went through the flows in the affected files but couldn't get logging to work in all places.
Managed to trigger the gem error path by disconnecting from network when clicking "Buy/Sell Crypto", and the same goes for useSendDetails errors with no network.

**Review by theoboldfrazier — APPROVED** [review]
Pulled down and tested. Looks good.

**Comment by cjthompson** [comment]
> You may need to set the new env var of `REACT_APP_LOG_LEVEL`

Yes. You need to set that to `trace` in your `.env` file. The default if the variable is not set is `info`.

**Pull request merged**
