### PR TITLE
fix: send revalidation not executed when going back and forth

### LINKED ISSUE #8035: [Bug] Incorrect user has reject the transaction error
image

We have a user that reach out to support with the following issues attempting to send USDT on polygon from an account with no POL (native asset). This is odd for a few reasons because on desktop we correctly block the action like this (created by spoofing their account)

image

A few things to note:

1. The from and to addresses are both valid (please ping me and I can provide them as needed )
2. They were able to recreate this issue repeatedly

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

If you first validate a send amount, then hit the back button, then directly go back to the amount screen, the validation is not executed anymore, so you can go further and finally fail at TX sending time because you don't have enough fee asset amount:

https://jam.dev/c/9193bccd-b2af-46a4-8354-ae542f7c66a8

## Issue (if applicable)

closes #8035

## Risk
Low
> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
See the jam in the description:
- Use any non-fee asset, using an account where you don't have any fee assets (ex: 1 USDT but 0 POL)
- Go to any send modal using the asset you have, go to the amount view and hit the max button, **you should see the red button with "You don't have enough funds" message**
- Hit back button, directly hit the next button and **see the blue button, you can go further but you don't have any fee assets**

### Engineering
n/a

### Operations
n/a
- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
https://jam.dev/c/e841a32e-f761-4f3e-9603-a3cdf48223f1

### CODE REVIEW

**Comment by kaladinlight** [comment]
https://github.com/user-attachments/assets/457edb94-002e-4318-8c96-1976cf82fd89

holding state when going back and forth, but seeing the state get invalidated initially. Happening on prod as well btw.

**Review by gomesalexandre — APPROVED** [review]
Very nice one ser! 

Repro'd in develop:

https://jam.dev/c/e139dbb4-eac0-472d-af9f-0d134e730c5a

And confirmed fixed in this diff:

https://jam.dev/c/a34306f8-4d6f-4b8a-ae3a-ce524de7c6cd

**Comment by NeOMakinG** [comment]
> 379c1ce

Nice catch, 100% related to the issue too, fixed 3 bugs on the send feature in one day seems like a good ratio 😆 

Fixed in [379c1ce](https://github.com/shapeshift/web/pull/8078/commits/379c1ce18c09f89358304e1af371121ba80cda38)

**Review by kaladinlight — APPROVED** [review]
looking gucci now!

**Pull request merged**
