### PR TITLE
fix: pairing of MM in in-app Android browser

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Does what it says on the box - ensures everything is nice and lazy to circumvent flaky `window.ethereum` injection in Android MM vs. iOS MM which is happy and seemingly stabler in that regard - see https://github.com/MetaMask/metamask-mobile/issues/3258 for more context.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/6334

Low - same flow as before but now lazy

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

**Note, this has been deployed to gome for ease of testing**

- Open the in-app MM browser in Android
- Ensure pairing works

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

- Prod

image

- This diff

image

### CODE REVIEW

**Comment by gomesalexandre** [comment]
* **#6492** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6492?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gomesalexandre and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by firebomb1** [comment]
Confirming connecting Metamask Mobile works on a hardware Android device again, thanks @gomesalexandre !

**Review by woodenfurniture — COMMENTED** [review]
Unfortunately I wasn't able to get this working on android via metamask browser, with brave as system default browser:
Screenshot_20240320-074155

Clicking "open" displays this warning:
Screenshot_20240320-074207

Clicking "allow" takes you to app store:
Screenshot_20240320-074213

Looks like it's on the correct commit:
Screenshot (20 Mar 2024 7_46_23 am)

**Comment by firebomb1** [comment]
Confirming that it's not working anymore :/

Unfortunately I have not taken note of the commit hash when I tested this as we were discussing in DM about the issue, so I'm not sure which of the commit above was deployed when I tested and it worked.

It might also be that the lazy checking is also working intermittently, and an async check based on the `ethereum#initialized` event [as suggested by MetaMask's doc](https://github.com/MetaMask/detect-provider/blob/main/README.md#synchronous-and-asynchronous-injection) would be more reliable 🤔

**Review by woodenfurniture — APPROVED** [review]
Noting this works for others and doesnt introduce any regressions, lets get this in

**Pull request merged**
