### PR TITLE
fix: unable to trade on non-evm assets on multi-hop ui

### PR DESCRIPTION
**Pull request by woodenfurniture**
## Description

Fixes broken trades from non-EVM assets when multi-hop ui is enabled.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

NA

## Risk

Low risk.

## Testing

Check trades selling non-EVM assets (rune, btc, ltc etc) work.

## Screenshots (if applicable)

https://github.com/shapeshift/web/assets/125113430/6db1bdc3-e77f-4ee7-881e-1190da1918dc

### CODE REVIEW

**Comment by woodenfurniture** [comment]
Current dependencies on/for this PR:
* `develop`
  * **PR #5846** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5846?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #5847** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5847?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5847?utm_source=stack-comment).

**Review by gomesalexandre — COMMENTED** [review]
Conceptual stamp pending runtime testing

**Review by gomesalexandre — COMMENTED** [review]
Tested locally:

- Allowance step is still happy for EVM assets

image
image


- Subsequent EVM trade is happy

image
image

### Non-EVM trades are still happy

Unable to test as trades are currently halted on all pools, will circle back to this once trading is active again

**Review by 0xApotheosis — APPROVED** [review]
Finishing @gomesalexandre's excellent testing now that THORChain trading is great again, confirmed able to trade non-EVM assets via the multi-hop interface.

**Pull request merged**
