### PR TITLE
feat: refactor staking data slice (#1652)

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
## Description

revert of the revert https://github.com/shapeshift/web/pull/1698

original PR https://github.com/shapeshift/web/pull/1652

original issue https://github.com/shapeshift/web/issues/1454

we had to back out this and the demo wallet PR in conjunction, as this PR was built on top of the demo wallet

it's not believed that this branch in and of itself caused any regressions, but will defer to @gomesalexandre 

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Did a full regression testing on this one after merging latest develop in:

### Staking

- It is possible to complete the flow and broadcast a stake Tx
- The available to stake amount matches the one in explorer

### Staking

- It is possible to complete the flow and broadcast an unstake Tx
- The available to unstake amount matches the one in explorer

### Overview

- It is possible to complete the flow and broadcast a claim Tx
- The staked amount matches the one in explorer
- The undelegations list matches the list from explorer

### Balances

- The `ATOM Staked` amount matches the one in explorer (delegated + undelegated)
- The total value matches the one in explorer

### Staking Opportunities

- The list of opportunities is shown and matches the one in explorer
- The rewards are shown and matching the ones in explorer
- The default validator is shown with "Get Started" in case there is no active staking (delegations/redelegations/undelegations/rewards)

### DeFi

#### Overview

- The list of opportunities is shown and matches the one in explorer
- The balance/APY matches the ones in explorer
- Clicking an active opportunity still opens the staking modal
- The wallet + earn balances are still totaling to the net worth

#### Earn

- The list of opportunities is shown and matches the one in explorer
- The balance/APR matches the ones in explorer
- The default validator is shown in case there is no active staking (delegations/redelegations/undelegations/rewards)
- Clicking a (default/active) opportunity still opens the staking modal
- Found a little regression in how we display the opportunities while loading, will improve the loading state before opening this for review: 
image

I also found what might be a regression in live update of staking data, but I'll need to double check against develop/prod to make sure it is a regression.

**Comment by gomesalexandre** [comment]
> I also found what might be a regression in live update of staking data, but I'll need to double check against develop/prod to make sure it is a regression.

Fixed by wrapping earn opportunities cells in a `<Skeleton />`: https://github.com/shapeshift/web/pull/1700/commits/03851f5e0d9e9f775ce4d9698f184c3d96e1d1c8

> I also found what might be a regression in live update of staking data, but I'll need to double check against develop/prod to make sure it is a regression.

Confirmed not a regression, live reload is also flaky in all environments currently. This doesn't seem to come from the cosmos staking implementation: I tried to console.log the `onMessage()` calls:
https://github.com/shapeshift/web/blob/954e2fc8f02b174337a36f4596adbe39f29505c1/src/state/slices/txHistorySlice/txHistorySlice.ts#L235-L236
Both in this branch and on prod/main, we don't have `onMessage()` calls, which would indicate this is either unchained, or the unchained WS connection on the client acting up. Tested with all staking actions, as well as sends and couldn't get any log to show up in console.
Either way, not related to this PR.

**Review by cjthompson — DISMISSED** [review]

**Comment by 0xdef1cafe** [comment]
"approved" from me - can't stamp my own PR

**Review by cjthompson — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
merging as per ops testing https://discord.com/channels/554694662431178782/973293513640914984

**Pull request merged**
