### PR TITLE
feat: thorchain LP handle fiat inputs

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Does what it says on the box

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

- relates to https://github.com/shapeshift/web/issues/6447 - note, we will use this issue to implement this for lending as well, so doesn't actually close it for now

Low, see testing

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

- Each input asset at THORChain LP add liquidity step has its own decoupled fiat toggling
- Toggling between crypto and fiat is happy

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

https://github.com/shapeshift/web/assets/17035424/96de1bbe-ff58-4152-8848-5bf7bc733cdc

### CODE REVIEW

**Comment by gomesalexandre** [comment]
* **#6468** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6468?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gomesalexandre and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by kaladinlight** [comment]
My first thought is we just have one state and handler and both amount change in tandem (ie. you are either viewing all inputs in crypto OR fiat as opposed to mixing formats). Thoughts?

**Comment by gomesalexandre** [comment]
> My first thought is we just have one state and handler and both amount change in tandem (ie. you are either viewing all inputs in crypto OR fiat as opposed to mixing formats). Thoughts?

Summoning @reallybeard here on how humans think of this, as a robot decoupled inputs are sane to me

**Comment by reallybeard** [comment]
@gomesalexandre This kinda goes into the, don't want to assume the user's intent. I could see a use case where a user wants to just input one asset in fiat and then see the equivalent amount in crypto. Very similar to how we currently handle it on trade.

Would this introduce too much complexity of keeping both of these inputs in sync of which value to show?

**Comment by gomesalexandre** [comment]
> @gomesalexandre This kinda goes into the, don't want to assume the user's intent. I could see a use case where a user wants to just input one asset in fiat and then see the equivalent amount in crypto. Very similar to how we currently handle it on trade.
> 
> Would this introduce too much complexity of keeping both of these inputs in sync of which value to show?

Having them coupled would in fact make this an almost one-liner instead - this PR has the logic for giving you the granularity of having them decoupled if you want to as a user!

**Comment by kaladinlight** [comment]
I thought trade had them tied together which is why I mentioned, and it's not like you can't see the crypto or fiat value in either case still. Just looked cleaner imo having the format look the same on both input fields (with bonus of less lines of code for it). Not a huge deal breaker either way, just was a thought

**Review by kaladinlight — APPROVED** [review]

**Pull request merged**
