### PR TITLE
fix: normalizeAmount should not round amounts up

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Fixes `normalizeAmount` rounding inputs up and making ZRX XHRs potentially fail on ERC-20s send maxes, since, depending on the actual balance for that address, the sellAmount we might be requesting might be off by a few weis from the actual balance of the address.

Note, at this point, `normalizeAmount` doesn't do much anymore and the new tests have been added to validate the implementation - we might want to ditch it entirely.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/4879

## Risk

None, does the same thing the original implementation intended to, minus the rounding.

## Testing

- ZRX quotes are happy, including with max. trades
- 1inch quotes are happy, including with max. trades

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

Postman replays have been redacted to keep only the `sellAmount` - note how the failing one on the current implementation rounds the amount up

### Develop/Prod

image
image

### This diff

image
image

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4894** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4894" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4894?utm_source=stack-comment).

**Review by kaladinlight — APPROVED** [review]

**Comment by kaladinlight** [comment]
Or I guess close this seeing the cleanup pr?

**Comment by gomesalexandre** [comment]
@gomesalexandre started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4894).

**Comment by gomesalexandre** [comment]
@gomesalexandre merged this pull request with [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4894).

**Pull request merged**
