### PR TITLE
feat: rambo remove osmosis

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Removes everything Osmosis 🩸 

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Testing

- ATOM asset page is happy
- ATOM account page is happy
- Cosmos native staking is happy
- Navigate around various accounts/asset pages, DeFi, search for ATOM and Osmo in the top-level search field and ensure no crash 

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

Screenshot 2023-08-22 at 12 56 21
Screenshot 2023-08-22 at 12 56 31
Screenshot 2023-08-22 at 13 47 30
Screenshot 2023-08-22 at 13 48 46
Screenshot 2023-08-22 at 13 48 55

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #5123** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5123" target="_blank">Graphite</a> 
    * **PR #5139** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5139" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5139?utm_source=stack-comment).

**Review by kaladinlight — APPROVED** [review]

**Comment by gomesalexandre** [comment]
@gomesalexandre started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5139).

**Comment by gomesalexandre** [comment]
[Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5139) rebased this pull request as part of a merge.

**Comment by gomesalexandre** [comment]
@gomesalexandre merged this pull request with [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5139).

**Pull request merged**
