### PR TITLE
feat: handle factory reset keepkey state

### LINKED ISSUE #1609: Handle factory-new KeepKey connections
### Overview

Upon connecting a factory-new KK -- or one which has been recovered after a failed firmware update -- the user gets dropped to this screen, which could be misleading if the user didn't initiate a wipe.

### References and additional details

Currently, when we receive a `NOTINITIALIZED` event from a KeepKey, we dispatch the `OPEN_KEEPKEY_INITIALIZE` action (assuming the user wiped it).

This even it also emitted when connecting a factory-new KeepKey.
We'll need a way to distinguish between a factory-new KeepKey that has not been initialized, and a KeepKey that has been wiped and needs to be re-initialized.

165401124-20b3d3ed-632a-41c6-a086-dbdc6bbf3495

### Acceptance Criteria

https://github.com/shapeshift/web/issues/1609#issuecomment-1112649156

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by brymut**
## Description

Handle the factory reset state on Keepkey based on A/C provided [here](https://github.com/shapeshift/web/issues/1609#issuecomment-1112649156). If modal is closed, redirected to the "Connect wallet" screen

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1609 

## Risk

Lower risk as changes scoped to UI related edits while wallet is still disconnected and Keepkey is still uninitialized/recently wiped. 

### Engineering

1. Disconnect existing connected wallet and plug-in factory reset or wiped keepkey wallet to device

2. Click "Connect wallet" and then  the Keepkey option and pair Keepkey wallet

3. Modal should appear with the requested title and description as requested in Acceptance criteria 

4. No back option should be available and closing modal should return user to the initial "Connect wallet" screen

### Operations

Same instructions apply as in engineering, or alternatively follow the screen recording below

## Screenshots (if applicable)

https://user-images.githubusercontent.com/14836056/187659154-d89fe8d5-e5bb-49a0-8f69-d9e6a1b6217b.mp4

### CODE REVIEW

**Comment by brymut** [comment]
Hi @gomesalexandre / @0xApotheosis could you please have a look?

**Comment by 0xdef1cafe** [comment]
@brymut please fill out the risk and testing sections, converting back to draft until you do so.

**Comment by brymut** [comment]
@0xdef1cafe done ✅

**Comment by brymut** [comment]
Hi, @0xdef1cafe / @gomesalexandre / @0xApotheosis could someone please have a look?

**Comment by brymut** [comment]
wesley graves#6768 on Discord has pointed out that the same "Get started with Keepkey" modal pops up again when closed immediately, I can see that its the "Device not initialized" event is being dispatched multiple times in the logs



https://user-images.githubusercontent.com/14836056/188086561-727772df-3c21-4acc-afab-faeb0ef0682f.mp4

**Comment by wesleygravess** [comment]
yep, this is an improvement because it takes you to the landing page (prod does not), but the "get started with keep key" modal pops up multiple times and it never takes you back to the connect a wallet menu, which is the desired behavior.

**Comment by brymut** [comment]
Hi @wesleygravess / @gomesalexandre could you please have another look?

**Comment by wesleygravess** [comment]
this is working for me now. clicking the x on the  "get started with keep key" modal takes you back to the landing page and the connect a wallet menu pops up

**Review by 0xdef1cafe — APPROVED** [review]
@brymut apologies for the delay on the review. i just tested this locally and confirmed it works. thanks for the contribution 🥇

**Pull request merged**
