### PR TITLE
fix: double gas fee deduction

### PR DESCRIPTION
**Pull request by Sliman4**
## Description

Fix double gas fee deduction. The gas fees are deducted here: https://github.com/shapeshift/web/blob/ddd08bad9526f8e67109ef4c49298ddf4d62686b/src/components/Trade/TradeInput.tsx#L86-L89
and the `estimatedGasFees` was also added to `tradeDeduction`, which resulted in double gas fee deduction in gas check.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Risk
I don't think anyone would really want to trade all of their ETH for other ERC-20 token because they won't have gas for trading it back, but the same risk also applies now, if the gas fees increase. The above `tradeDeduction` comment says "when trading from ETH, the value of TX in ETH is deducted", and nothing about double fee deduction, so that's not the intended behavior.

## Testing

Try to trade `your all eth - estimated gas fee` for any other token, and you'll get "Not enough ETH to cover gas".

### CODE REVIEW

**Comment by cjthompson** [comment]
would it be better to remove the extra subtraction from `hasEnoughBalanceForGas` rather than from `tradeDeduction`? Is `tradeDeduction` used it other places where the fee should also be removed?

**Review by cjthompson — APPROVED** [review]

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
This does appear to address the double gas fee bug, nice find 👍

However, something is still not right, and the problem described in the issue is not fixed. 

On this branch, when I click "Max" ETH for the trade I still get the "Not enough ETH to cover gas" error. 

If I lower the amount calculated by "Max' I can then make the trade.

**Comment by gomesalexandre** [comment]
> This does appear to address the double gas fee bug, nice find 👍
> 
> However, something is still not right, and the problem described in the [linked issue](https://github.com/shapeshift/web/issues/1527) is not fixed.
> 
> On this branch, when I click "Max" ETH for the trade I still get the "Not enough ETH to cover gas" error.
> 
> If I lower the amount calculated by "Max' I can then make the trade.

Just tried it and same here for me. I've debugged it locally and while the calculation seems correct now, we do have a negative number when deducting `feeAssetBalance - estimatedGasFees - tradeDeduction`.
It looks like we're getting wrong gas estimation/swapper quotes and because of that, this whole calculation fails at `gt(0)` check.

**Comment by gomesalexandre** [comment]
@Sliman4 Is this still in a reviewable state given the latest comments? I've tried with your latest commit but unfortunately I'm still experiencing the same bug.
That looks good for what it does specifically, so happy to either accept it if you remove mention of #1527 and tackle it specifically in a separate PR, or you can move this one to draft in the meantime and continue here.

**Comment by Sliman4** [comment]
Yeah, the bug that I was going to fix is the double gas fee deduction, but @tshifty has created an issue and pinged me on discord, I misread it (both the message and the issue) and just linked it to this pr. It's actually 2 separate bugs, so I think I'll just unlink the issue and revert the second commit. By the way, [dd7664f](https://github.com/shapeshift/web/pull/1529/commits/dd7664f757b9730292d6a1a0b50c8407015d331d) is related to the double fee deduction bug, covering its edge case.

As I made this pr just because I've noticed it while exploring source code and don't have eth on mainnet (and I guess there's no possibility to run this on testnet yet), I'll leave #1527 to someone who can properly fix and test it.

**Review by gomesalexandre — APPROVED** [review]
> Yeah, the bug that I was going to fix is the double gas fee deduction, but @tshifty has created an issue and pinged me on discord, I misread it (both the message and the issue) and just linked it to this pr. It's actually 2 separate bugs, so I think I'll just unlink the issue and revert the second commit. By the way, [dd7664f](https://github.com/shapeshift/web/pull/1529/commits/dd7664f757b9730292d6a1a0b50c8407015d331d) is related to the double fee deduction bug, covering its edge case.

Sounds good! Thanks for the info, looks good now without #1527 linked/mentioned. Nice work on spotting this, and great work!! 

> As I made this pr just because I've noticed it while exploring source code and don't have eth on mainnet (and I guess there's no possibility to run this on testnet yet), I'll leave #1527 to someone who can properly fix and test it.

Yeah you're right, we don't support testnets... yet! 😉 

#1527 is a tricky one with implications that go possibly further than a simple calculation fix on the client, we might get around that in the shorter term by over-estimating but we'll definitely need to fix estimations at the root cause.

**Review by 0xApotheosis — APPROVED** [review]
Nice one, I'm happy with this now without the linked issue 👍 

Thanks for the contribution @Sliman4!

**Pull request merged**
