### PR TITLE
fix: language selector on very small mobiles and homepage margin

### LINKED ISSUE #7062: lang selector is over the title on responsive splash screen
### Overview

If you use ShapeShift with the Metamask mobile app, the lang selector is over the title and so it makes it difficult to read/notify that it exists

image

### References and additional details

- Use MetaMask browser on mobile
- Navigate to https://app.shapeshift.com

### Acceptance Criteria

TBD by @shapeshift/product 

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description
- Fixed the very small mobile language selector going over the text, it might add a scroll bar but on very small mobile I feel like it's a nice trade off and the scrollbar isn't so big
- Also changed the margin of the login component

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #7062

## Risk
Low risk

## Testing
- Inspect and open the homepage with a really small mobile view like `iPhone SE`, the lang selector should not be over the text anymore
- The margin of the login component should be equal from left to right

### Engineering
n/a

### Operations
n/a

## Screenshots (if applicable)
image
image

### CODE REVIEW

**Review by gomesalexandre — COMMENTED** [review]
LGTM on desktop and mobile responsives, testing pending on mobile app and mobile browser https://jam.dev/c/986da3cb-f1e3-4708-9aeb-d3f6b73e1124

**Comment by firebomb1** [comment]
Great fix, thanks!

We can have the same kind of overlap on very small height resolutions on the `src/pages/ConnectWallet/MobileConnect.tsx` page, not sure if you'd want to tackle this at the same time with the same type of positioning?

mobile

**Comment by NeOMakinG** [comment]
> Great fix, thanks!
> 
> We can have the same kind of overlap on very small height resolutions on the `src/pages/ConnectWallet/MobileConnect.tsx` page, not sure if you'd want to tackle this at the same time with the same type of positioning?
> 
> mobile

As discussed in private, the usecase is more about when you use the wallet with the splitscreen feature on android, but the problem is not only about this language selector but the whole page with a scroll, it's even worse if you add multiple wallets, also I'm not sure the rest of the app is designed to be used in a little square 😆 

This is a nice catch btw, but in term of value, I'm not sure that this is something we wan't to work on

Can you confirm @shapeshift/product ?

**Review by gomesalexandre — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Merging so it's not blocking, depending on the product decision we'll just act as a follow up

**Pull request merged**
