### PR TITLE
chore: disable osmo chain everywhere

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
## Description

turns off OSMO chain entirely

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

n/a

## Risk

low, turns off feature flags

## Testing

- osmo shouldn't appear anywhere in the app

### Engineering

👆

### Operations

👆

### CODE REVIEW

**Review by woodenfurniture — APPROVED** [review]

**Review by 0xApotheosis — COMMENTED** [review]
This makes navigating to the Cosmos asset very sad. Did we want to remove the asset from the generated list?

Screenshot 2023-08-22 at 10 56 13 am

**Comment by 0xdef1cafe** [comment]
yeah this makes a few things sad. we can't get rid of ATOM as we're not disabling cosmos chain. lemme fix.

**Review by 0xApotheosis — COMMENTED** [review]
The Cosmos asset is great again.

A little weird that we show a swapper with the Cosmos asset that'll never have any routes - it should really auto-set to our default asset pair.

Screenshot 2023-08-22 at 11 18 51 am

**Comment by 0xdef1cafe** [comment]
as discussed the inability to get atom -> eth quotes via TC is currently in prod and not specific to this PR, wanna shippity dip?

**Comment by 0xApotheosis** [comment]
Ship ship hooray.

**Pull request merged**
