### PR TITLE
feat: enable thorchain lp

### PR DESCRIPTION
**Pull request by 0xApotheosis**
Known issues:

- [x] Tx confirmed mutation never gets fired
- [x] No back button once get to waiting for confirmation screen: https://github.com/shapeshift/web/pull/6392
- [x] ~Can't toggle to fiat amount~ (won't do before release, large lift)
- [x] fee estimation is triggered symetrically even for asym which can lead in estimation failures
- [x] https://github.com/shapeshift/web/issues/6395
- [x] https://github.com/shapeshift/web/issues/6413 (we may or may not want to get this in prior to launch)
- [x] https://github.com/shapeshift/web/issues/6412
- [x] https://github.com/shapeshift/web/issues/6441
- [x] Add MixPanel support (https://github.com/shapeshift/web/pull/6464)

---

Ditching the usual PR template here in favor of a testing plan. See the chart below for LP types incompatibilities when testing

oh god

### Notes

- ⚠️  Given the gotchas of incompatibilities between LP types, and given the fact we haven't yet implemented UI to block/inform users re: incomplete Txs, it's *highly* recommended to only test with only one active position at a time. Test the full deposit/withdraw flow, once exited from the pool, try with another. 
- Test with all assets - one native EVM asset, one EVM token, ATOM, at least one UTXO, and obviously RUNE
### Available LP opportunities tab

- All opportunities are correctly fetched and displayed
- APY looks sane
- Pool name, TVL, Volume 24h and Volume 7D looks sane (compare against THORYield though discrepancies are obviously expected because of timeframe differences as well as *more* accurate calculations on our part)
- Clicking an opportunity goes to the LP pool page

### LP pool page

- Metrics in "Pool Information" look sane (compare against THORYield though discrepancies are obviously expected because of timeframe differences as well as *more* accurate calculations on our part)
- Trade correctly links to buying said pool asset

### LP positions tab

- Active positions are correctly reflected, with a tag showing the LP type for said position
- Balance, earnings and pool share looks sane (compare against THORYield though discrepancies are obviously expected because of timeframe differences as well as *more* accurate calculations on our part)
- Clicking the position links to the position page

### Position page

- Balance, earnings and pool share looks sane (compare against THORYield though discrepancies are obviously expected because of timeframe differences as well as *more* accurate calculations on our part)
- The prorated amount of each asset is looking sane
- Metrics in "Pool Information" look sane (compare against THORYield though discrepancies are obviously expected because of timeframe differences as well as *more* accurate calculations on our part)
- Refer to Deposits and Withdraws section below for the specific testing required for these

### Standalone "Add Liquidity" page

- Wallet support is detected and reflected depending on the asym type selected/asset e.g:
  - Trying to do ETH/RUNE sym will be detected as no wallet support in MM
  - Trying to do ETH/RUNE asym on the asset (ETH) side will be detected as happy wallet support in MM with no error
  - Trying to do BTC/RUNE in MM will be detected as no wallet support in MM regardless of the LP type chosen

### Deposits

- Approvals are properly triggerred for tokens when required, and *not* triggerred if allowance >= amount
- Sweeps are properly triggerred for UTXO when required (do a self-send to your next receive address, which should trigger a sweep, and ensure it is then triggerred when depositing)
- Rebalancing of assets when depositing sym (50/50) looks sane
- Note, fiat amount input is not implemented
- Max sends are happy (note: we're not yet doing fee deduction yet, so it will obviously fail quote on out of gas for native assets)
- ShapeShift fee is correctly shown according to the LP fee curve

#### Sym/asym

- When depositing symetrically, RUNE Tx is triggerred first. After confirmation, asset Tx is triggerred. When the asset Tx complete, the deposit shows as completed and position updates in the UI
- When depositing asym, there is only one Tx. When the Tx completes, the deposit shows as completed and position updates in the UI

### Withdraws

- There is never an approval step here
- Sweeps are properly triggerred for UTXO when required (do a self-send to your next receive address, which should trigger a sweep, and ensure it is then triggerred when withdrawing)
- There is no fee curve for withdraw, as there are no affiliate bps on withdraws

#### Sym/asym

- When withdrawing sym, there is only a a RUNE Tx required to withdraw both
- When doing sym, the required Tx is either RUNE for RUNE, or an asset chain Tx for asset
- When the withdraw completes in the UI, the position properly updates

### CODE REVIEW

**Comment by 0xean** [comment]
@shapeshift/operations - if there is a test document that we could review for this one it might be useful so that engineering can help guide any missing test cases and also tackle some of the testing internally.

**Comment by 0xean** [comment]
@MBMaria - it would be good to get a status update on testing and a follow up re: the testing plan.  We need to get this feature moving along if possible.

**Comment by gomesalexandre** [comment]
Withdraw is possible for sym positions on MM (which should be impossible, because the withdraw Tx is a RUNE Tx)

image

**Comment by MBMaria** [comment]
> @MBMaria - it would be good to get a status update on testing and a follow up re: the testing plan. We need to get this feature moving along if possible.

sorry for the delay @0xean . i was in the emergency rooms all day yesterday as i fractured my elbow. right arm is in a cast so i will be a little slow with the remainder of the resting but ill do my best to get it done. reading the PR it looks pretty thorough on what to test, i'm thinking ill make that into a spreadsheet which we can mark off as complete once each step is tested.

**Comment by 0xean** [comment]
> > @MBMaria - it would be good to get a status update on testing and a follow up re: the testing plan. We need to get this feature moving along if possible.
> 
> sorry for the delay @0xean . i was in the emergency rooms all day yesterday as i fractured my elbow. right arm is in a cast so i will be a little slow with the remainder of the resting but ill do my best to get it done. reading the PR it looks pretty thorough on what to test, i'm thinking ill make that into a spreadsheet which we can mark off as complete once each step is tested.

Ouch, thanks for letting me know and hope you aren't in too much pain!

**Comment by gomesalexandre** [comment]
### Asym UTXO deposit

image
image
image
image

🚫 Tx confirmed mutation never gets fired

This isn't an LP specific issue, though the mutation only fires on Tx complete, which isn't detected by us. This could be a me issue as many of my Txs never seen to confirm in the app (big Tx history problem?), but we should probably remove the `TxStatus.Confirmed` condition

image

### 100% UTXO withdraw
 
image
image
image

🚫 Ditto, Tx confirmed mutation never gets fired for the same reason as above

image

### Asym EVM token deposit

- Allowance needed is detected and approval triggered

image

🚫 allowance needed still present after on-chain confirmation, perhaps something to do with account 1 ? 
image

**Comment by MBMaria** [comment]
1) no back button once get to waiting for confirmation screen
image

2) Usually this toggles to enter a fiat amount. currently can only enter a btc figure
image

**Comment by twblack88** [comment]
( つ ◕_◕ )つ
mixpanel plz
( つ ◕_◕ )つ

**Review by gomesalexandre — APPROVED** [review]
it's happening

**Pull request merged**
