### PR TITLE
chore: add apy to env file

### LINKED ISSUE #1469: Pull FOXy APY from env var
### Overview

We need to be able to update this with two clicks, rather than a lib pr and a web pr and a prod release.

### References and additional details

Add a `REACT_APP_FOXY_APY` env var that is consumed to display the APY.

### Acceptance Criteria

FOXy APY is pulled from an env var, not hard coded.

### Need By Date

n/a

### Screenshots/Mockups

_No response_

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### PR DESCRIPTION
**Pull request by toshiSat**
## Description

add FOXy APY to env file to make it easier to change until they complete their api

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
closes #1469

### CODE REVIEW

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
I'm wary of adding too many specific environment variables like this, but if we were to do it we should use `getConfig().REACT_APP_FOXY_APY` to access it.

**Comment by toshiSat** [comment]
Added a better way to set APY, now we just need to remove those three lines from web once Tokemak has an api to get reactor info from

**Comment by toshiSat** [comment]
> 

This is temporary.  We are waiting until Tokemaks API gets setup in 1-2 weeks to be able to easily calculate APY

**Review by 0xApotheosis — APPROVED** [review]
That's nicer 👍

**Review by 0xdef1cafe — APPROVED** [review]
REACT_APP_FOXY_APY has been added to fleek and cloudflare with a value of `.12` as of 4/13

**Pull request merged**
