### PR TITLE
feat: consume new swapper base unit vernacular

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Consumes the changes made in https://github.com/shapeshift/lib/pull/1122.

Technically the swapper change is a non-breaking change, but there is actually a slight logic change here, given we were relying on and mirroring the types, and thus naming, of swapper's `fees?.chainSpecific` in web. As a result of this we were getting things mixed up.
Currently in develop, `fees?.chainSpecific.approvalFee` initially starts from lib swapper as being a base unit, but somehow, it silently becomes a precision amount. This was a bug waiting to happen:

https://github.com/shapeshift/web/blob/bf610098e582c9f8d968096c64a5a2385cc47eca/src/components/Trade/hooks/useSwapper/utils.ts#L103-L105
https://github.com/shapeshift/web/blob/bf610098e582c9f8d968096c64a5a2385cc47eca/src/components/Trade/hooks/useSwapper/utils.ts#L110-L112

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A, smallish subset of base units refactor

## Testing

- Swapper input shows no regressions
- Swapper quotes show no regression (try swapping buy/sell assets out and ensure this looks good)
- Swapper "Not enough <asset> for gas" flow shows no regression
- Swapper fees show no regressions

### Engineering

☝🏽 

### Operations

☝🏽

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #3475** <a href="https://app.graphite.dev/github/pr/shapeshift/web/3475" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/3475?utm_source=stack-comment).

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
This has broken our rate ratio calculation:

Screenshot 2022-12-21 at 12 00 18 pm

Vs expected:

Screenshot 2022-12-21 at 12 00 39 pm

**Comment by 0xApotheosis** [comment]
The issue above is with the underlying lib PR, not this one.

I've made a fix in https://github.com/shapeshift/lib/pull/1139, which once merged will make this problem go away.

**Comment by 0xApotheosis** [comment]
TODO: merge https://github.com/shapeshift/lib/pull/1139 and update the swapper package to that published version.
Then retest this PR, it should be good to go.

**Review by 0xApotheosis — APPROVED** [review]
With https://github.com/shapeshift/lib/pull/1139 published and consumed by this PR we should be good to go now.

**Pull request merged**
