### PR TITLE
fix: not showing BTC balances

### LINKED ISSUE #239: BTC USD Balance is wrong on dashboard

### PR DESCRIPTION
**Pull request by cjthompson**
## Description

Fix not showing BTC balances

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Closes #239 

## Testing

Please outline all testing steps

1. Connect a wallet with a BTC balance
2. Go the BTC asset page
3. Click on the different script types
4. wait for the balance to update

## Screenshots (if applicable)
p2sh-p2wpkh
image

p2sh
image

### CODE REVIEW

**Review by kaladinlight — APPROVED** [review]
Nice catch

**Comment by elmutt** [comment]
Do we also want to do this in the other places we get public keys using toPath?

here is one of them:

https://github.com/shapeshift/web/blob/develop/src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx#L110

**Review by elmutt — APPROVED** [review]

**Comment by cjthompson** [comment]
> Do we also want to do this in the other places we get public keys using toPath?
> 
> here is one of them:
> 
> https://github.com/shapeshift/web/blob/develop/src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx#L110

This needs to be done wherever we're asking for an xpub for a UTXO coin. If we're just getting a specific address at a path, we can use the whole 5 deep path. 

I'll take a look at that code you referenced.

**Comment by cjthompson** [comment]
> Do we also want to do this in the other places we get public keys using toPath?
> 
> here is one of them:
> 
> https://github.com/shapeshift/web/blob/develop/src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx#L110

Good catch. It looks like we need the same change there as well.

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
