### PR TITLE
fix: update fox discount threshold from 1M to 300k

### PR DESCRIPTION
**Pull request by reallybeard**
## Description

- We need to update the threshold from 1M to 300k

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #

high risk

> What protocols, transaction types or contract interactions might be affected by this PR?

### Engineering

This seemed like the correct place to change this. 

### Operations

Open the fee modal on trade, you should see FREE once the FOX Holdings are over 300k.

## Screenshots (if 
Screenshot 2024-03-19 at 3 58 42 PM
applicable)

### CODE REVIEW

**Review by 0xApotheosis — APPROVED** [review]
gm

**Comment by purelycrickets** [comment]
@reallybeard or @twblack88 Do we want to change the slider for FOX power to be 0-300K instead of 0-1MM now that we have lowered the threshold?

**Comment by purelycrickets** [comment]
Screenshot 2024-03-20 at 1 05 05 PM


Free trades now trigger at ~35% of the slider length.

**Comment by twblack88** [comment]
Fine for now with the arrow indicator but we should consider that yeah.

**Pull request merged**
