### PR TITLE
fix: directly redirect to dashboard when connecting to a wallet

### LINKED ISSUE #1467: Update wallet connection modal flow
### Overview

Currently, when connecting a Wallet (any ShapeShift supported wallet) to the shapeshift web app, upon successful pairing of the wallet the user is shown a success modal (pictured below).

Going forwards we want to use this modal only to show error messaging. So if the pairing is successful there should be no modal and the user should be viewing the dashboard.

If there is any issue with the pairing process this modal should pop up and display the appropriate error messaging.

### References and additional details

web code base.  NEED additional info from engineering

### Acceptance Criteria

A/C:
After successfully pairing a wallet to the web app the user should be directed straight to the dashboard. If the user's Wallet has an issue pairing then the error is displayed in the modal.

### Need By Date

n/a

### Screenshots/Mockups

Screen Shot 2022-04-11 at 2 03 44 PM

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

hours

### Sponsor / Stakeholder

@FOX_McCloud

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description
- When we connect a wallet, we want to directly redirect to the dashboard instead of showing a success modal
- I kept some success modal => Native wallet recovery, creating wallet, keepkey recovery, maybe the product team should validate this 

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
closes #1467

## Risk
- No real risk except a wrong use flow

## Testing
Try to connect with:
- Metamask
- Portis
- Keepkey
- Native wallet
You shouldn't see any success modal

## Screenshots (if applicable)
https://www.awesomescreenshot.com/video/8443721?key=0d4cc994996155367c39ff34c4d1f0a9

### CODE REVIEW

**Review by 0xApotheosis — APPROVED** [review]
Looks good. 

I wonder if a toast would be more appropriate to replace the success modal - something unintrusive that disappears on its own. One for product.

**Review by gomesalexandre — COMMENTED** [review]
One thing with this is it's hard to review this with the context of this PR alone.

The reducer case for `WalletActions.SET_WALLET_MODAL` for reference:

https://github.com/shapeshift/web/blob/fc3bd3eef1971823a87b67d42b5bee82df88f4c7/src/context/WalletProvider/WalletProvider.tsx#L96-L106

And the typings definition:

https://github.com/shapeshift/web/blob/fc3bd3eef1971823a87b67d42b5bee82df88f4c7/src/context/WalletProvider/actions.ts#L42

It would probably make sense to either:

- Make the payload optional so we only pass true explicitly and falsy implicitly by not passing anything
- Make it something like `{shouldForgetRoute: boolean}` instead of `boolean` - what do you think?

**Review by gomesalexandre — APPROVED** [review]
Tested and LGTM.
Agreed with @0xApotheosis it would be great to still have some kind of, although less intrusive, feedback.

Added `needs product` to #1467 but I'll already accept this one.

**Comment by 0xdef1cafe** [comment]
as discussed with @SS-FOX-McCloud let's merge this and if product wants we can add a toast in a separate PR

**Pull request merged**
