### PR TITLE
chore: re-enable lifi swapper

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

- As per https://x.com/lifiprotocol/status/1813519919373590763, re-enables the LiFi swapper.
- Restricts LiFi approvals to be "exact amount" only (all other swappers are unaffected)

Effectively reverts https://github.com/shapeshift/web/pull/7380, but also consolidates the feature flag to just be in `base`.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

Small.

> What protocols, transaction types or contract interactions might be affected by this PR?

LiFi swapping.

## Testing

LiFi swapper should be enabled again, and work as expected.

### Engineering

☝️

### Operations

☝️

## Screenshots (if applicable)

**LiFi swap requiring approval**

Screenshot 2024-07-18 at 2 36 31 PM

**Other swaps requiring approval**

Screenshot 2024-07-18 at 2 36 06 PM

### CODE REVIEW

**Comment by 0xean** [comment]
@twblack88 - do we want this back on immediately? Think this is a product call vs an engineering call.

I know there are some routes that are blocked without lifi but would like to raise the question.

**Comment by twblack88** [comment]
Can we control for unlimited approvals?

0x is doing the permit2 thing so maybe that's the best pattern to pull from

**Comment by 0xean** [comment]
We can default to exact amounts rather than unlimited (currently we give users the option, but default to unlimited), but we currently don't have out of the box permit functionality ready to go and would require a product spec and seperate work from this PR. We would also need to confirm that Lifi supports permits for tokens that have the functionality.

**Comment by twblack88** [comment]
cool! sorry for the delay in response, I'm aligned with turn it back on and have only exact amount approvals. Will work on a `permit2` spec.

**Comment by 0xApotheosis** [comment]
Ok, more work to do to allow only exact-allowance approvals - I'll put this back in draft until we have a path forward on that.

**Comment by 0xApotheosis** [comment]
Re-opened, LiFi swap approvals are only able to be completed for the exact trade amount.

**Comment by kaladinlight** [comment]
image
image

confirmed forced exact allowance and successful trade

**Comment by 0xean** [comment]
@kaladinlight - very nice testing ser

**Review by kaladinlight — APPROVED** [review]

**Pull request merged**
