### PR TITLE
feat: thorchain LP Tx sent toast

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Does what it says on the box

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

- contributes to https://github.com/shapeshift/web/issues/6405

None, this does the toast thing

> What protocols, transaction types or contract interactions might be affected by this PR?

## Testing

- After broadcasting an LP (deposit/withdraw) Tx, a toast toasts.

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

image

### CODE REVIEW

**Comment by gomesalexandre** [comment]
* **#6556** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6556?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gomesalexandre and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
The toast does indeed toast!

Screenshot 2024-03-26 at 11 01 53 AM

However, I think it's firing before we have a `txId`, as the URL, when clicked, is `https://viewblock.io/thorchain/tx`.

**Comment by gomesalexandre** [comment]
> We we have a `txId`, as the URL, when clicked, is `https://viewblock.io/thorchain/tx`.

@0xApotheosis seems like we had some little shadowing going on - fixed in ced05a9cf68b6fa6e140d5504090251cc29195e0 !

**Review by 0xApotheosis — APPROVED** [review]
A little shadowing, indeed!

That did the trick, toast now happily provides the correct TX URL.

**Pull request merged**
