### PR TITLE
feat: cowswap tx parser

### LINKED ISSUE #2218: consume cowswap tx parser
### Overview

requires https://github.com/shapeshift/lib/issues/901

### References and additional details

see lib issue for details

### Acceptance Criteria

we can correctly render cowswap trades in web

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
## Description

- [x] can parse cowswap txs
- [x] uses dynamic dex name for order route from parsed tx
- [x] dex names have been updated to user facing brand values, e.g. `thor` is now `THORChain`

TODO

- [x] requires unchained-client package bump to consume new parser from https://github.com/shapeshift/lib/pull/909
- [x] how to render fees @shapeshift/product - hidden for now if no fees on trade
Screen Shot 2022-07-25 at 6 48 38 PM

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #2218

## Risk

0x trades are interpreted as cowswap trades

## Testing

* enable cowswap flag
* do a cowswap trade (any erc20 -> erc20) will route via cowswap by default
* ensure that trade renders as per screenshot

## Screenshots (if applicable)

before

image

after

image

### CODE REVIEW

**Review by gomesalexandre — COMMENTED** [review]
I tested this one out with the matching lib PR, unfortunately, that's not rendering as it should, I'm seeing the exact same compared to develop, the reason for that being this cheeky switch statement where we fall back to the default branch:

https://github.com/shapeshift/web/blob/5f41bc1a6aa777fe9d90d602dfa707eb0e441854/src/components/TransactionHistoryRows/TransactionRow.tsx#L57-L68

The reason for that is `txDetails.type` is `Trade` while the value of `TradeType.Trade` is `trade`, see: 

https://github.com/shapeshift/lib/blob/7b4e7565f15707d494c2c7ddfd499113f53fc04b/packages/chain-adapters/src/types.ts#L120
image

Piggybacking to your [comment](https://github.com/shapeshift/lib/pull/909/files#r929434058) on the lib PR, we have a duplicates `TradeType` enum on `chain-adapters` (that we use in that switch statement), and `unchained-client` (that we use to render the trade type), both using a different casing.

We should consolidate them into a single type. For the time being, using the `chain-adapters` version in the lib PR will fix the issue for Cowswap, but note that ZRX and Thor parsers are affected by the same issue.

**Comment by kaladinlight** [comment]
> I tested this one out with the matching lib PR, unfortunately, that's not rendering as it should, I'm seeing the exact same compared to develop, the reason for that being this cheeky switch statement where we fall back to the default branch:
> 
> https://github.com/shapeshift/web/blob/5f41bc1a6aa777fe9d90d602dfa707eb0e441854/src/components/TransactionHistoryRows/TransactionRow.tsx#L57-L68
> 
> The reason for that is `txDetails.type` is `Trade` while the value of `TradeType.Trade` is `trade`, see:
> 
> https://github.com/shapeshift/lib/blob/7b4e7565f15707d494c2c7ddfd499113f53fc04b/packages/chain-adapters/src/types.ts#L120 image
> 
> Piggybacking to your [comment](https://github.com/shapeshift/lib/pull/909/files#r929434058) on the lib PR, we have a duplicate `TradeType` enum on `chain-adapters` (that we use in that switch statement), and `unchained-client` (that we use in the parser as the trade type), both using a different casing.
> 
> We should consolidate them into a single type.
> 
> For the time being, using the `chain-adapters` version in the lib PR will fix the issue for Cowswap, but note that ZRX and Thor parsers are affected by the same issue so they should also use the version with the right casing.

Yes, the casing was changed in the lib PR, it works as it was, but I agree we should consolidate these types now that unchained-client is in lib. See: https://github.com/shapeshift/lib/pull/909/files#r930077009

**Review by kaladinlight — DISMISSED** [review]

**Review by gomesalexandre — DISMISSED** [review]
Tested again with the latest lib package bumps included, parsing is working fine for Cow Swaps in all Tx history components

Also tested 0x swaps which are parsed similarly

image
image

**Review by gomesalexandre — APPROVED** [review]
Tested again with the latest commit, 0 fees are hidden

**Review by kaladinlight — APPROVED** [review]

**Pull request merged**
