### PR TITLE
fix: language selector for iphone

### LINKED ISSUE #4925: Language drop down menu on connect page on mobile app too high
### Overview

When trying to select a different language on mobile, the drop down menu is too high and you cant access it

### References and additional details

1) open mobile app 
2) notice language selector at the top right hand corner
3) note it is too high and you cannot access the drop down menu
*iphone 14
image

### Acceptance Criteria

should be able to access language drop down menu

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Estimated effort

_No response_

### Sponsor / Stakeholder

_No response_

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

### PR DESCRIPTION
**Pull request by firebomb1**
## Description

Fixes the Language selector on the Connect Wallet page being inaccessible on iPhone 14 due to the Dynamic Island.

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #4925 

## Risk
Low.

## Testing
Check if the Language selector is fully visible and usable on iPhone.
Check that it remains at the same place on other devices.

### Engineering
☝️ 

### Operations
☝️ 

## Screenshots (if applicable)
Mobile resolution (unfortunately no way to test this personally, @gomesalexandre said he would do some testing on iPhone)
image

No changes visible from the current situation, it should only affect browsers/devices which report a smaller viewport due to OS UI elements like the Dynamic Island from iPhone.

### CODE REVIEW

**Comment by firebomb1** [comment]
Thinking about this again, this fix might not work for this, the language selector will likely still be behind the Dynamic Island...

We could fix this by making the dropdown element into a Menu element from Chakra UI and have a small icon top left or top right to open it to select a language. With a smaller footprint it would be have less chances to be under an OS UI element... But I'm not convinced an exception for iPhone is a good idea (such exception make maintenance annoying).

Open to suggestion to change this, I'm also not sure it's something we should fix, because [apparently it's possible to hide this OS UI element](https://www.xda-developers.com/how-to-disable-dynamic-island-ios/) temporarily to access, so it might just be the user not knowing they can do it?

**Comment by firebomb1** [comment]
Apparently iOS Safari (and hopefully the webview we use in the iOS mobile app) [sets few CSS environment variables](https://itnext.io/make-your-pwas-look-handsome-on-ios-fd8fdfcd5777) in relation to the safe area with regards to the notch/Dynamic Island. This last commit should actually help us position the Language selector better on devices which use these features.

**Review by gomesalexandre — APPROVED** [review]
Tested on iPhone 14 pro both in-browser and bookmarking it as a PWA to get it full-screen, LGTM! tyvm ser 

IMG_1597

IMG_1598

Also confirmed we still look good on desktop 🤌

**Comment by firebomb1** [comment]
Thanks for the tests and review, glad the blind/no-test fixing worked 😄

**Pull request merged**
