### PR TITLE
feat: cow fee model changes

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

This implements the change in CoW fee model, where fees will soon (March 19th) have to be paid in token *alongside* the order

- [x] implement fees at order-level
- [x] implement fee balance checks - CoW is the only swapper doing this weirdness, and we will need to handle this - maxes aren't maxes anymore
- [ ] ~~handle the CoW weirdness in maxes~~ we can't do that, chicken-and-egg scenario

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes https://github.com/shapeshift/web/issues/6261

- Not a risk per se but inherent to this, max token swaps for CoW will inherently be broken - can be tackled in a follow-up by either being smart with a buffer, or doing a double quote of sorts on max click - get quote for max amount, deduct fees, set that as a sell amount which will trigger a new quote
- Ensure no regression in other swappers because of wrong payable protocol fees deduction checks

> What protocols, transaction types or contract interactions might be affected by this PR?

- CoW
## Testing

- Max or very close to max CoW swaps are now failing at "not enough <token> for gas" error
- Orders are sent with the fee *alongside* the order

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

### CoW max swap

Screenshot 2024-03-14 at 16 09 11

### Li.Fi max swap

Screenshot 2024-03-14 at 16 09 21

### Fees are sent alongside the order

image
image
image
image
image

- Note 18.16 FOX sell amount but 18.1642 FOX actually sold

image

### CODE REVIEW

**Comment by gomesalexandre** [comment]
* **#6455** <a href="https://app.graphite.dev/github/pr/shapeshift/web/6455?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @gomesalexandre and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xApotheosis — CHANGES_REQUESTED** [review]
Implementation looks sane, though at a first pass functional test I'm noting a regression where I'm unable to get CoW quotes for routes we can quote for in production:

Screenshot 2024-03-15 at 9 17 50 AM

**Comment by gomesalexandre** [comment]
> Implementation looks sane, though at a first pass functional test I'm noting a regression where I'm unable to get CoW quotes for routes we can quote for in production:
> 
> Screenshot 2024-03-15 at 9 17 50 AM

@0xApotheosis can you try with an integer amount of 1000 FOX and confirm you see no regressions? As discussed, this is a different issue which may sometimes lead us to think CoW is broken in a PR, or things are "randomly" breaking", but really look like an issue with precision where too many dp results in failure to get quotes (either that, or another non-deterministic issue upstream):

image

**Review by 0xApotheosis — APPROVED** [review]
Hmm, I'm able to replicate these intermittent issues on production, too, so it's not an issue with this PR.

You're right, the quote issue seems to be something to do with caching, as often changing the amount slightly gets a quote again.

**Pull request merged**
