### PR TITLE
feat: buy button in the header for mobile

### LINKED ISSUE #3491: On mobile add a buy button to the header that links to the buy page
### Overview

We would like to add a global buy button in the top header section that user can click to go to the page buy.

### References and additional details

Add a button to the `Header` component that takes you to the buy/sell crypto page. This should only show up on mobile.

### Acceptance Criteria

Buy button that links to the buy/sell page shows on mobile in the header.

### Need By Date

_No response_

### Screenshots/Mockups

dashboard-buy-example

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by firebomb1**
## Description

- Displays a "Buy" button in the Header for mobile/low resolution, available on all pages.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #3491

## Testing

On low width viewports/mobile verify the presence and function of the new Buy button.

### Engineering
☝️ 

### Operations
☝️ 

## Screenshots (if applicable)
English
image

French (active state while on the Buy page)
image

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
@reallybeard @firebomb1 

image

can you coordinate on this plz?

**Comment by reallybeard** [comment]
> @reallybeard @firebomb1
> 
> image
> 
> can you coordinate on this plz?

Guess we gotta match the same button size as the wherever thing --- or we make the wherever one small.

**Comment by firebomb1** [comment]
> Guess we gotta match the same button size as the wherever thing --- or we make the wherever one small.

I'm fine with a larger Buy button personally, I only made it small to match your mockup but didn't realize there was a new button next to it now :D

**Comment by firebomb1** [comment]
In English it's ok, it's a tighter fit in French (as usual... 🙄). For even narrower width the logo gets pushed to the left with no overlap (unless it's an unrealistically small width).

image

image

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
