### PR TITLE
feat: use IPFS link for social sharing thumbnail

### LINKED ISSUE #958: Fix PUBLIC_URL to enable IPFS deployments

### PR DESCRIPTION
**Pull request by mrnerdhair**
## Description

This eliminates the dependency on `PUBLIC_URL` to make social sharing embed magic work, which will help make builds consistent across deployments.

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

Helps fix #958. (Will also need env var tweaks in the build pipeline after this.)

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
@mrnerdhair looks great, what do we need to get this out of draft?

**Comment by mrnerdhair** [comment]
@reallybeard what do you think about this approach? The idea is that `PUBLIC_URL` can be blank, but the IPFS image preview will still work. Note that we do have to lose the `og:url` tag -- there's just no way to know at compile-time what to fill in there without using `PUBLIC_URL` and messing up build reproducibility -- but it's optional and I can't find any practical impact of omitting it.

**Comment by cjthompson** [comment]
I'm concerned about hardcoding a requirement on IPFS. Why not just keep the `PUBLIC_URL` environment variable and just change it to IPFS for those that want to use it.

**Comment by mrnerdhair** [comment]
If `PUBLIC_URL` has to differ for every deployment at a different URL, it'll mean build hashes differ for every deployment. It'll also mean that you can't mirror the site at a different URL (say, by using a different IPFS gateway) -- or at least not if you want your twitter thumbnail to work. Nothing in the code requires that `PUBLIC_URL` be set except for twitter thumbnails, and it makes no sense to me to compromise on build verifiability to make the screaming bird happy.

A normal user will never see or load the URL in the `og:image` meta tag at all, so I don't think it really counts as adding a dependency on IPFS. (The alternative would be to make every deployment hard-code the thumbnail link to `https://app.shapeshift.com/thumbnail.jpg`, which IMO makes a lot less sense than hardcoding it to Cloudflare's IPFS gateway.)

**Review by theoboldfrazier — APPROVED** [review]

**Comment by cjthompson** [comment]
I think this is exaggerating the problem. The hash will be the same given the same input URL.

But this isn't a hill I care to die on.

**Review by cjthompson — APPROVED** [review]

**Pull request merged**
