### PR TITLE
fix: update env to use better nodes

### PR DESCRIPTION
**Pull request by elmutt**
## Description

These are much more reliable nodes.

I am not updating this in `config.ts` and `bootstrap.yml` and `pr-cypress.yml` files because I don't want to expose the api key in code. Those are still set to the older less reliable public nodes. I believe this should be fine as long as we have .env values populated for debug, fleek and prod?

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Risk

low risk behind feature flag

## Testing

n/a

### CODE REVIEW

**Review by gomesalexandre — COMMENTED** [review]
Will we have to update these with our API key locally everytime we do `cp sample.env .env`? If so, that seems like a lot of friction. You mention `Those are still set to the older less reliable public nodes` but if copying sample.env to .env, these will be used.

What's the goal of this, to provide more reliable nodes for local development, or to provide more reliable nodes for Fleek envs?
If that's the former, then API key should be present.
If that's the latter, then it could be set directly on Fleek, with the API key, and we could delete these two entries altogether, which will make localhost default to the values in `src/config.ts`.

**Comment by elmutt** [comment]
> 

It's for local development, these same value will be set for fleek, prod & dev. With my local testing this works fine as long as the feature flag is already set to true in the .env but your right -- I do see it using the older nodes if I start with the feature flag off and toggle it on in-app.

My main concern was including the api key in the code base which is generally bad practice. However in this situation it might not be important as the key is still available in the frontend to anyone so inclined to extract it. I just thought putting it in the repo and showing it to the world so easily isn't great

Im open to suggestions tho, if we decide its easiest & best to include the api key in code maybe thats the best?

**Comment by 0xdef1cafe** [comment]
> > 
> 
> It's for local development, these same value will be set for fleek, prod & dev. With my local testing this works fine as long as the feature flag is already set to true in the .env but your right -- I do see it using the older nodes if I start with the osmo feature flag off and toggle it on in-app.
> 
> My main concern was including the api key in the code base which is generally bad practice. However in this situation it might not be important as the key is still available in the frontend to anyone so inclined to extract it. I just thought putting it in the repo and showing it to the world so easily isn't great
> 
> Im open to suggestions tho, if we decide its easiest & best to include the api key in code maybe thats the best?

i think so - we already have the infura key in there and others. in the event that we are obviously getting scraped for keys, we can obfuscate .env vars like base64 them to avoid bots, but ultimately we can't secure them, they're available to the client as a `env.json` file.

**Comment by elmutt** [comment]
@0xdef1cafe @gomesalexandre sounds good to me. updated

**Review by gomesalexandre — DISMISSED** [review]
LGTM, ran locally and didn't find Cosmos/Osmosis regressions (tested balance charts / sends / advanced features)

**Comment by 0xdef1cafe** [comment]
env vars updated in dev/app/private

**Review by 0xdef1cafe — APPROVED** [review]

**Pull request merged**
