### PR TITLE
feat: add config to check if app is running in mobile

### PR DESCRIPTION
**Pull request by cjthompson**
## Description

The `globalThis.isShapeShiftMobile` will be set to true via injected JavaScript from the new mobile app.

I've verified that the injected JavaScript runs before `config.ts` and returns true. This config variable can be used in the future to show different content as needed (such as a different wallet flow for the mobile app).

## Notice

- [X] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [X] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
N/A
## Risk
None. The worst case is that `isMobile` reports `false` when it should report `true`.
## Testing
Requires new mobile app for testing
## Screenshots (if applicable)
Mobile
image

Desktop
image

### CODE REVIEW

**Review by 0xApotheosis — COMMENTED** [review]
This looks reasonable, though does it need to be in the config at all?

Can we just use `Boolean((globalThis as any).isShapeShiftMobile)` in-line wherever we need to do conditional logic on it?

**Comment by gomesalexandre** [comment]
> This looks reasonable, though does it need to be in the config at all?
> 
> Can we just use `Boolean((globalThis as any).isShapeShiftMobile)` in-line wherever we need to do conditional logic on it?

In addition to whether or not we need it here at all, I believe this breaks the current abstraction.

The mental model of `getConfig()` is it's just a dotenv kept in sync with the flags on the redux store. It feels weird to have it be almost exclusively a flags accessor except for the one window var shoehorned there.

**Comment by 0xdef1cafe** [comment]
@cjthompson agreed with @gomesalexandre and @0xApotheosis - we similarly made this decision here to not pollute `config.ts` with non-`.env` related changes

https://github.com/shapeshift/web/pull/2209#discussion_r931647153

i'm happy for this to be exposed closely to config, but keeping config's single concern the `.env` file

**Comment by cjthompson** [comment]
I thought of config as runtime variable vs constants. This isn't a constant. I'll happily implement whatever suggestion you provide.

**Comment by cjthompson** [comment]
> This looks reasonable, though does it need to be in the config at all?
> 
> Can we just use `Boolean((globalThis as any).isShapeShiftMobile)` in-line wherever we need to do conditional logic on it?

Certainly you could. But that argument applies equally to `config.ts` and `constants.ts`. All of those could just be inlined.

The argument for not going that is easier maintenance for future devs.

@0xdef1cafe asked me to make a `lib/globals.ts` file with the code in it so I'll submit an update with that change.

**Comment by cjthompson** [comment]
Note that `globals.ts` doesn't currently get imported anywhere. There will be some future work around the new mobile app that will take advantage of this.

**Review by gomesalexandre — APPROVED** [review]

**Review by 0xApotheosis — APPROVED** [review]
LGTM. Thanks for removing that unneeded `merge`, too.

**Pull request merged**
