### PR TITLE
feat: make zrx swapper wallet agnostic

### PR DESCRIPTION
**Pull request by woodenfurniture**
## Description

Upgrades zrx swapper to the wallet-agnostic pattern as part of our move to an SDK style integration of swappers in web.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

progresses https://github.com/shapeshift/web/issues/5024 (but doesn't close it)

## Risk

High risk of broken swappers, especially zrx. Specifically trade execution.

## Testing

* Check all swappers still work
* Check zrx trades still work

### Engineering

☝️

### Operations

☝️

## Screenshots (if applicable)
image

### CODE REVIEW

**Comment by woodenfurniture** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #5223** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5223" target="_blank">Graphite</a> 
    * **PR #5224** <a href="https://app.graphite.dev/github/pr/shapeshift/web/5224" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/5224?utm_source=stack-comment).

**Review by 0xApotheosis — APPROVED** [review]
Very tidy code-wise. As with the previous, I'll defer to @MBMaria's functional testing.

**Review by gomesalexandre — COMMENTED** [review]
Conceptual stamp so far - approval pending the ops-spotted failed quote is fixed in case allowance isn't granted yet

**Review by 0xApotheosis — APPROVED** [review]
Re-reviewed the changes in https://github.com/shapeshift/web/pull/5224/commits/a57bd8f8c6ee25a068a514292f089d5e31742540.

This is sane, though does rely on the quote fetch after approval not changing materially, which is something to consider in the future.

**Pull request merged**
