### PR TITLE
chore: skip flakey tests

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

The commented tests are flakey. I'm not yet sure why, but I'm removing them until I do.

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

N/A

## Testing

`yarn test:cypress`

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Review by 0xdef1cafe — APPROVED** [review]

**Review by theoboldfrazier — APPROVED** [review]

**Review by gomesalexandre — APPROVED** [review]

**Comment by 0xApotheosis** [comment]
Hold up, this is re-based wrong. Need to fix.

**Review by cjthompson — APPROVED** [review]

**Comment by cjthompson** [comment]
does cypress have a `skip` function as an option over just commenting out code?

**Comment by 0xApotheosis** [comment]
> does cypress have a `skip` function as an option over just commenting out code?

Excellent point @cjthompson - added `skip()` in https://github.com/shapeshift/web/pull/1115/commits/a17841a83c47cdf3ee0a8556192a7349d4259d1d.

**Comment by 0xApotheosis** [comment]
Closing in favour of https://github.com/shapeshift/web/pull/1117

**Pull request closed without merging**
