### PR TITLE
fix: add some missing CSP lines

### LINKED ISSUE #603: Add CSP support for yearn & coincap
We merged the new CoinCap and Yearn market data providers but didn't add Content Security Policy (CSP) whitelisting in web - the new services aren't able to make network requests and won't work till we add this.

Add the following URLs to https://github.com/shapeshift/web/blob/develop/headers.js#L13

- https://raw.githack.com/trustwallet/assets/master/blockchains/ethereum/
- https://api.github.com/repos/yearn/yearn-assets/contents/icons/multichain-tokens/1
- https://api.coincap.io/v2/assets

Request a review from @reidrankin on your PR when you're done.

### PR DESCRIPTION
**Pull request by reidrankin**
## Description

Closes #603.

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

### CODE REVIEW

**Comment by reidrankin** [comment]
@0xdef1cafe can you verify that https://api.coincap.io/v2/assets is the correct URL? if the requests are going to a sub-path instead it'll need a trailing `/`

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
> @0xdef1cafe can you verify that https://api.coincap.io/v2/assets is the correct URL? if the requests are going to a sub-path instead it'll need a trailing `/`
> 
> Edit: Checked, it is. Updated with permalinks.

this is going to a subpath yes, it will need the `/`

**Comment by reidrankin** [comment]
> this is going to a subpath yes, it will need the `/`

Now I'm confused -- I looked it up in `lib` and it looks like it's not? (for CSP, query strings don't count)
I put permalinks into document the source of each rule, did I miss one somewhere?

**Comment by 0xdef1cafe** [comment]
Screen Shot 2021-12-22 at 6 54 01 AM

@reidrankin see error from the console. we can't guarantee it will always be `/ethereum` either, so trailing slash is better

**Comment by reidrankin** [comment]
Ah, caip requires the no-slash version and market-service needs the slash version. Should be sorted now.

**Pull request merged**
