### PR TITLE
feat: revert of the revert of "fix(UserMenu): locked metamask not rec…

### LINKED ISSUE #1262: Metamask doesn't reconnect when locked
### Overview

Wallets automatically reconnect on page refresh if they're unlocked. MetaMask will become locked and require a password after some period of time. If MetaMask is in this state, we spin forever and never notify the user to unlock MetaMask.

### References and additional details

See the video for reproduction steps

https://user-images.githubusercontent.com/88504456/159733073-769b573e-6639-4d48-9bcf-c391528cbaad.mov

It might be worth first investigating if we're even able to query this state from MetaMask. This may require a PR into [hdwallet](https://github.com/shapeshift/hdwallet/).

### Acceptance Criteria

 - Turn the wallet button into a button group
 -  move the dropdown arrow into its own IconButton. That way when the wallet button is in a loading state you can still expand the menu.
 

### Need By Date

n/a

### Screenshots/Mockups

_No response_

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

### PR DESCRIPTION
**Pull request by gomesalexandre**
…onnecting (https://github.com/shapeshift/web/pull/1667)"
a.k.a the revert of the revert

Requires https://github.com/shapeshift/hdwallet/pull/528 to be published before, and hdwallet deps updated before this goes to review.

## Description

Added a button group to separate the dropdown button while wallet is stuck in a loading state when Metamask is locked

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1262 

## Testing
- set your MetaMask autolock to 1 minute
- there should be a button to reconnect automatically locked MetaMask
- there should be no regressions in connecting a MetaMask wallet

## Screenshots (if applicable)

https://user-images.githubusercontent.com/14836056/166608288-62e27d26-5b38-4884-8000-468f7e057098.mov

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
@brymut are you able to take a look at this please? we had to back #1667 out of develop as it caused regressions, and develop was not able to connect to metamask.

this hdwallet PR was just merged to publish a new version https://github.com/shapeshift/hdwallet/pull/530

you'll need to update to hdwallet `1.21.2` in a new commit in this PR, and check it works again.

**Comment by gomesalexandre** [comment]
@0xdef1cafe Pushed bumped hdwallet packages to latest and gave it one more test connecting/waiting for auto-lock, works just as when I was linking hdwallet-metamask

**Comment by 0xdef1cafe** [comment]
tested working by ops as per https://discord.com/channels/554694662431178782/974442760247578664/974800402786689045

**Review by 0xdef1cafe — APPROVED** [review]

**Review by 0xApotheosis — APPROVED** [review]
Have reviewed this before, and just re-tested - it still works as expected.

🍬

**Comment by 0xdef1cafe** [comment]
yeah gave this another thorough test myself, everything behaves as expected.

**Pull request merged**
