### PR TITLE
feat: language selector for mobile connect

### PR DESCRIPTION
**Pull request by firebomb1**
## Description
Adds the language selector  on the Mobile connect screen to match the feature available to non-mobile users and allow users to select their preferred language when they are on-boarding.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

Low. Existing component re-used.

> What protocols, transaction types or contract interactions might be affected by this PR?

None.

## Testing
On mobile make sure that the language selector appears with the rest of the UI elements and works.
Note: The buttons in certain languages will overflow. This is fixed by another PR (#7063) and shouldn't block this.

### Engineering
☝️ 

### Operations
☝️ 

## Screenshots (if applicable)
Loading:
image

English:
image

Spanish:
image

French (Note: overflowing captions of button should be ignored as they will be fixed in #7063):
image

### CODE REVIEW

**Review by reallybeard — APPROVED** [review]
LGTM just a few small suggested changes.

**Comment by firebomb1** [comment]
Good suggestions @reallybeard ! I've actually applied them to the non-mobile Connect page too as the code is very similar and had these strings declared the same way. Thanks!

**Comment by reallybeard** [comment]
> Good suggestions @reallybeard ! I've actually applied them to the non-mobile Connect page too as the code is very similar and had these strings declared the same way. Thanks!

Awesome thank you!

**Review by NeOMakinG — APPROVED** [review]
image

Looks good!

**Pull request merged**
