### PR TITLE
feat: nft refresh button (revert of the revert)

### PR DESCRIPTION
**Pull request by 0xApotheosis**
Re-opening for @gomesalexandre. It was merged, as it was working for me locally, but then we were having node issues and ops couldn't test: see https://discord.com/channels/554694662431178782/1115110431808299130 thread.

## Description

WIP as Polygon unchained is currently borked, so we can't test this yet

This PR:

- adds an NFT refresh button, getting a single NFT metadata from Alchemy
- if the NFT is a Polygon NFT *with IPNS meta* (not IPFS - we can only get meta, thus medias, from IPNS gateway links), we use our unchained media, which is refreshed on query
- is the NFT is an Optimism/Mainnet NFT, this uses the regular Alchemy parsing logic

While at it, exposes `http` in all ethereum plugins, to make things nice and reusable and not have to write wrappers over all `V1Api` method in chain-adapters

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

None, this is isolated as a new feature - work case scenario, this doesn't work (which it doesn't at the time of writing because of our Polygon node being down)

## Testing

- Customize your FOXatar
- Click the refresh icon
- Ensure your FOXatar is refreshed with his new fancy traits

### Engineering

- ☝🏽 

### Operations

- ☝🏽 

## Screenshots (if applicable)

image

https://github.com/shapeshift/web/assets/17035424/c8ac38c3-3c7d-405f-b0ac-019a2f65bdd4

### CODE REVIEW

**Comment by 0xApotheosis** [comment]
@gomesalexandre I noticed something interesting in the alchemy response.

The `media.gateway` value (which we seem to be using) has a URL to the default foxatar, whereas the `media.thumbnail` URL and `media.raw` IPFS link to the actual, updated foxatar.

`metadata.image` also link to the correct, updated foxatar.

Are we using the correct keys, here?

**Comment by gomesalexandre** [comment]
> @gomesalexandre I noticed something interesting in the alchemy response.
> 
> The `media.gateway` value (which we seem to be using) has a URL to the default foxatar, whereas the `media.thumbnail` URL and `media.raw` IPFS link to the actual, updated foxatar.
> 
> `metadata.image` also link to the correct, updated foxatar.
> 
> Are we using the correct keys, here?

Discussed this one out - as we're aware, the Alchemy API rugs us with old data, and the only reason why `media.thumbnail` and `metadata.image` *may* be correct is because we've waited long enough (many, many minutes) for the metadata to eventually refresh, but as a refresh flow, this isn't reliable.

Agreed to add a fallback to the fallback as a follow-up, using the introspected IPNS meta

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4646** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4646" target="_blank">Graphite</a>  👈
    * **PR #4647** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4647" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4646?utm_source=stack-comment).

**Review by 0xdef1cafe — APPROVED** [review]
posterity stamp per juicyman

`[7:42 AM]Apotheosis: For sure, the bottom of that stack (4646) as already been reviewed and production ready. Let's review 4647 and then get them both in together.`

**Pull request merged**
