### PR TITLE
fix: handle long asset names in send input

### LINKED ISSUE #7720: Send input styling is borked for long asset names
### Overview

Currently when trying to send tokens with long names e.g some pool assets, styling is borked and the name overflows:

image

### References and additional details

N/A

### Acceptance Criteria

Either:

- Use asset symbol instead of name or
- Trim asset name with ellipsis if too long

### Need By Date

_No response_

### Screenshots/Mockups

_No response_

### Estimated effort

_No response_

### PR DESCRIPTION
**Pull request by woodenfurniture**
## Description

Fixes text overflow of asset label in send input.

Adds a ellipsis for overflow with tooltip.'

Opted to use `trimWithEndEllipsis` intead of CSS ellipsis so we can predictably and simly detect an overflow render the tooltip accordingly.

## Issue (if applicable)

closes #7720

## Risk

> High Risk PRs Require 2 approvals

Low risk - display concern only.

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

Check normal length asset names are rendered correctly without a tooltip.
Check very long asset names are truncated with an ellipsis and have a tooltip with the full asset name.

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

https://github.com/user-attachments/assets/02d9119a-5301-42a4-b0d8-33bf28a15cc8

### CODE REVIEW

**Review by gomesalexandre — CHANGES_REQUESTED** [review]
Tested locally, and while name does ellipse now, there are still issues re: overflowing array as well as symbol still rugging the send display: 

https://jam.dev/c/3723bfe2-5d04-472d-9fbe-1d7ff71e024c

See arrow placement/symbol rugging "Enter Amount" with long symbols vs. smolish ones:

image
image

**Comment by woodenfurniture** [comment]
> Tested locally, and while name does ellipse now, there are still issues re: overflowing array as well as symbol still rugging the send display:
> 
> https://jam.dev/c/3723bfe2-5d04-472d-9fbe-1d7ff71e024c
> 
> See arrow placement/symbol rugging "Enter Amount" with long symbols vs. smolish ones:
> 
> image image

Well spotted, changed approach to use css variables and looking much better:

image

image

**Comment by woodenfurniture** [comment]
Also added some overflow for amounts

image

**Review by gomesalexandre — APPROVED** [review]
Retested locally, second time's a charm!

image

Still noticing the same issue re: symbol being weird but should be much more simple to tackle separately in a follow-up :fridaydoge:

image

**Pull request merged**
