### PR TITLE
fix: incorrect data field in transaction creation

### PR DESCRIPTION
**Pull request by woodenfurniture**
## Description

Fixes broken trades where data is added to `contractData` instead of `data`

The origin of this issue appears to be here
https://github.com/shapeshift/web/commit/4c4a86e4e0b5c8a8b04ca10a0830b546a568726a#diff-e1c07bf5d2e33ec33ad78ade8314e7848cbf1db824b59fa82c040747b0a748b5R87

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

NA

## Risk

Although this fixes complete broken trades and approvals and gas estimates, its high risk nonetheless. 

## Testing

Check trades and gas estimates are working as expected.

### Engineering

See above. Please sanity check this with extreme paranoia.

### Operations

See testing notes. This is high risk, although it fixes an issue of broken trades and gas estimates.

### CODE REVIEW

**Comment by woodenfurniture** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4843** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4843" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4843?utm_source=stack-comment).

**Review by 0xApotheosis — APPROVED** [review]
Good catch, pre stamp pending ops approval.

**Comment by 0xApotheosis** [comment]
@kaladinlight @gomesalexandre turbo important to sanity check this, and ensure it goes out as part of the next release.

Fixes https://github.com/shapeshift/web/commit/4c4a86e4e0b5c8a8b04ca10a0830b546a568726a#diff-e1c07bf5d2e33ec33ad78ade8314e7848cbf1db824b59fa82c040747b0a748b5R87.

**Review by gomesalexandre — COMMENTED** [review]
Post-develop merge testy for sanity check purposes:

- With this guy reverted

Screenshot 2023-06-27 at 10 01 09
Screenshot 2023-06-27 at 10 00 30

- With this commit in

image
image
image
image

**Pull request merged**
