### PR TITLE
fix: make approve icon relative size and scroll on the nav drawer

### PR DESCRIPTION
**Pull request by reallybeard**
## Description

- Instead of hardcoding the approve icon, we can make it relative to the asset icon size.
- Allow scrolling on the drawer when the screen is smaller

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

n/a

## Risk

n/a

## Testing

- Approve icon shows as relative size to the asset icon on all views of TX history
- For the scrolling navbar, on smaller screen sizes the drawer should scroll to allow you access all the nav items.

## Screenshots (if applicable)
Screen Shot 2022-08-22 at 3 50 40 PM
Screen Shot 2022-08-22 at 3 50 44 PM
Screen Shot 2022-08-22 at 3 50 50 PM

### CODE REVIEW

**Review by 0xApotheosis — COMMENTED** [review]
The approve icons look good. Re: the scrollable draw, the one below?
If so, I wasn't able to scroll it.

Screen Shot 2022-08-23 at 7 07 59 am

**Comment by reallybeard** [comment]
> The approve icons look good. Re: the scrollable draw, the one below? If so, I wasn't able to scroll it.
> 
> Screen Shot 2022-08-23 at 7 07 59 am

Its when you are in a drawer view not the normal view.

**Comment by 0xdef1cafe** [comment]
yeah @0xApotheosis works for me

image

**Review by 0xApotheosis — APPROVED** [review]
Ok, it worked on the Fleek link. 

Local environment something something...

**Pull request merged**
