### PR TITLE
feat: upgrade react-router-dom

### LINKED ISSUE #675: upgrade react-router-dom
# Overview

We currently use `react-router-dom` on version `5.2.0` and want to update to the latest major version, as of writing, `6.2.1`.

There is an [example closed PR here](https://github.com/shapeshift/web/pull/469) showing what is required.

This will mainly involve fixing type errors and breaking changes throughout the app and will take some time to get all of the errors fixed after the upgrade.

# Acceptance Criteria

- App is fully functional with no regressions
- CI passes, i.e. lint/type-check/build/test

# Bounty Hunters
- Join our discord [here](https://discord.gg/shapeshift).  Feel free to ask for help in #engineering-public channel
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
taking over original PR from https://github.com/shapeshift/web/pull/695 to manage merge conflicts and get deployed internally

## Description

Upgrade React Router 

close #675

## Ref
- https://typescript.tv/react/upgrade-to-react-router-v6/
- https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
@cjthompson this compiles and builds but shits the bed at runtime - see the cloudflare link. could you take another look please?

**Comment by cjthompson** [comment]
We cannot do this upgrade. `react-router-dom` v6 [removes the ability to use nested routers](https://github.com/remix-run/react-router/issues/7375). We use multiple `<MemoryRouter>`s within the default `<BrowserRouter>`. 

We will need to revamp completely how we do routing. This also means that we may have to rethink how we do routing for plugins. We may have to have plugins export all of their routes to work with v6 (or choose another router module?).

**Comment by gomesalexandre** [comment]
> We cannot do this upgrade. `react-router-dom` v6 [removes the ability to use nested routers](https://github.com/remix-run/react-router/issues/7375). We use multiple `<MemoryRouter>`s within the default `<BrowserRouter>`.
> 
> We will need to revamp completely how we do routing. This also means that we may have to rethink how we do routing for plugins. We may have to have plugins export all of their routes to work with v6 (or choose another router module?).

What's the rationale to using `MemoryRouter` as a nested router? If it is to have "independent" (or rather reusable) subrouters, isn't it possible to use e.g The `${path}/relative` syntax where path would be either `somePath` (nested route) or `''` (independent route)?. `MemoryRouter`s should be for contexts that don't have access to the browser (history) API, typically Node tests.

I think by keeping the nested routers nested, but not making them memory routers anymore, we would be able to upgrade. Not sure about the plugin implications here.

**Comment by cjthompson** [comment]
> > We cannot do this upgrade. `react-router-dom` v6 [removes the ability to use nested routers](https://github.com/remix-run/react-router/issues/7375). We use multiple `<MemoryRouter>`s within the default `<BrowserRouter>`.
> > We will need to revamp completely how we do routing. This also means that we may have to rethink how we do routing for plugins. We may have to have plugins export all of their routes to work with v6 (or choose another router module?).
> 
> What's the rationale to using `MemoryRouter` as a nested router? If it is to have "independent" (or rather reusable) subrouters, isn't it possible to use e.g The `${path}/relative` syntax where path would be either `somePath` (nested route) or `''` (independent route)?. `MemoryRouter`s should be for contexts that don't have access to the browser (history) API, typically Node tests.
> 
> I think by keeping the nested routers nested, but not making them memory routers anymore, we would be able to upgrade. Not sure about the plugin implications here.

My point is only that the way we are doing routing will require more work to change before we can upgrade and those changes were not known when the ticket was written and were not in scope of the ticket.

**Comment by gomesalexandre** [comment]
> My point is only that the way we are doing routing will require more work to change before we can upgrade and those changes were not known when the ticket was written and were not in scope of the ticket.

Oh, precisely. There is no way to implement this at 0 cost by just bumping react-router and adapting to the breaking changes, that's right!

**Pull request closed without merging**
