### PR TITLE
feat: add zrx API key

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

Does what it says on the box - note this is a ZRX-provided key with a 2 weeks grace period and 25rps, shared across all clients which is realistically really small.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Testing

- Ensure ZRX is happy. Note this will be inherently flaky with the 25rps - even a single or two users getting ZRX quotes + ops testing at the same time may make quotes fail

### Engineering

- Ensure 0x requests use the `0x-api-key` header

### Operations

- This may or may not unrug 0x for affected users - confirmed XHRs were responding without any error and I was able to get ZRX quotes

## Screenshots (if applicable)

image
image
image

image
image
image
image

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4697** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4697" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4697?utm_source=stack-comment).

**Comment by gomesalexandre** [comment]
Closing for now, may cause us more trouble than it solves until we have an enterprise key - will reopen when we do

**Comment by gomesalexandre** [comment]
Reopening as draft following https://twitter.com/0xProject/status/1677376955749105665:

> Starting Monday, July 10th, access to 0x APIs will only be available to registered customers with an API key.

**Review by 0xApotheosis — APPROVED** [review]
0x working correctly in testing with this key, we'll see how 25 rps fairs in production.

**Pull request merged**
