### PR TITLE
chore: move investor-idle into lib

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

Move `investor-idle` package into lib.

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

Theoretically small - if webpack builds, and the all works locally, we should be good.

## Testing

- webpack should build as expected
- the app, particularly in relation to `investor-idle`, should work just as it did before

### Engineering

☝️

### Operations

☝️

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by 0xApotheosis** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4505** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4505" target="_blank">Graphite</a> 
    * **PR #4506** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4506" target="_blank">Graphite</a> 
      * **PR #4507** <a href="https://app.graphite.dev/github/pr/shapeshift/web/4507" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4507?utm_source=stack-comment).

**Review by woodenfurniture — DISMISSED** [review]

**Comment by 0xApotheosis** [comment]
@0xApotheosis queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4507).

**Comment by 0xApotheosis** [comment]
[Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4507) rebased this pull request as part of a merge.

**Comment by 0xApotheosis** [comment]
[Graphite](https://app.graphite.dev/github/pr/shapeshift/web/4507) couldn't merge this PR because it was not satisfying all requirements.

**Pull request merged**
