### PR TITLE
feat: add @typescript-eslint/consistent-type-imports rule

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

This adds the [`@typescript-eslint/consistent-type-imports`](https://typescript-eslint.io/rules/consistent-type-imports/) eslint rule and autofixes all lint violations after adding it. 

Uses the default `{ prefer: "type-imports", disallowTypeAnnotations: true }` options.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/blob/develop/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

None

## Testing

- If CI is happy, we are 🛍️ 

### Engineering

- See top-level notes

### Operations

- Nothing to see here

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #2691** <a href="https://app.graphite.dev/github/pr/shapeshift/web/2691" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/web/2691?utm_source=stack-comment).

**Comment by 0xdef1cafe** [comment]
hoooo boy you gonna `.git-blame-ignore-revs` after this one?

**Comment by gomesalexandre** [comment]
> hoooo boy you gonna `.git-blame-ignore-revs` after this one?

Yes ser will do! We need to wait for this to be squashed and merged first as we can't predict the commit hash of the commit 🔮

**Review by 0xApotheosis — DISMISSED** [review]
Very nice, I've been wanting to do this for some time.

I've skimmed this change and it all looks as expected.

**Comment by 0xdef1cafe** [comment]
@gomesalexandre @0xApotheosis merge conflicts were impossible - i reset the branch off develop, added the rule and ran `yarn lint:fix` again

**Comment by 0xApotheosis** [comment]
Ah dammit, rugged by `foxy multi-account` before I could get to it.

**Review by 0xApotheosis — APPROVED** [review]
Let's get this bad boy in before more conflicts occur.

**Pull request merged**
